In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from pathlib import Path

BASE = Path("/content/drive/MyDrive/Chattogram_Landmark_Dataset")

FOLDERS = [
    "01_inventory",
    "02_availability",
    "03_candidates",
    "04_review",
    "05_final_dataset",
    "06_reports",
    "07_cache"
]

for folder in FOLDERS:
    (BASE / folder).mkdir(parents=True, exist_ok=True)

print("Project directory:")
print(BASE)

for folder in FOLDERS:
    print("✓", BASE / folder)

Project directory:
/content/drive/MyDrive/Chattogram_Landmark_Dataset
✓ /content/drive/MyDrive/Chattogram_Landmark_Dataset/01_inventory
✓ /content/drive/MyDrive/Chattogram_Landmark_Dataset/02_availability
✓ /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates
✓ /content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review
✓ /content/drive/MyDrive/Chattogram_Landmark_Dataset/05_final_dataset
✓ /content/drive/MyDrive/Chattogram_Landmark_Dataset/06_reports
✓ /content/drive/MyDrive/Chattogram_Landmark_Dataset/07_cache

In [ ]:
!pip -q install requests pillow tqdm imagehash pandas matplotlib

In [ ]:
LANDMARKS = {

    # ============================================================
    # CHATTOGRAM
    # ============================================================

    "Patenga_Beach": {
        "district": "Chattogram",
        "queries": [
            "Patenga Beach Chittagong",
            "Patenga Beach Chattogram",
            "Patenga Bangladesh"
        ]
    },

    "Foys_Lake": {
        "district": "Chattogram",
        "queries": [
            "Foys Lake Chittagong",
            "Foy's Lake Chittagong",
            "Foys Lake Chattogram"
        ]
    },

    "Parki_Beach": {
        "district": "Chattogram",
        "queries": [
            "Parki Beach Chittagong",
            "Parki Beach Anwara",
            "Parki Sea Beach Bangladesh"
        ]
    },

    "Chandranath_Hill": {
        "district": "Chattogram",
        "queries": [
            "Chandranath Hill Sitakunda",
            "Chandranath Hill Chittagong",
            "Chandranath Bangladesh"
        ]
    },

    "Chandranath_Temple": {
        "district": "Chattogram",
        "queries": [
            "Chandranath Temple Sitakunda",
            "Chandranath Temple Bangladesh",
            "Chandranath Mandir Sitakunda"
        ]
    },

    "Sitakunda_Eco_Park": {
        "district": "Chattogram",
        "queries": [
            "Sitakunda Eco Park",
            "Sitakunda Ecopark Bangladesh",
            "Sitakunda Eco Park Chittagong"
        ]
    },

    "Guliakhali_Beach": {
        "district": "Chattogram",
        "queries": [
            "Guliakhali Beach",
            "Guliakhali Sea Beach",
            "Guliakhali Chittagong"
        ]
    },

    "Banshbaria_Beach": {
        "district": "Chattogram",
        "queries": [
            "Banshbaria Beach",
            "Banshbaria Sea Beach",
            "Banshbaria Chittagong"
        ]
    },

    "Kalurghat_Bridge": {
        "district": "Chattogram",
        "queries": [
            "Kalurghat Bridge",
            "Kalurghat Railway Bridge",
            "Kalurghat Bridge Chittagong",
            "Kalurghat Bangladesh"
        ]
    },

    "Shah_Amanat_Bridge": {
        "district": "Chattogram",
        "queries": [
            "Shah Amanat Bridge",
            "Shah Amanat Bridge Chittagong",
            "Shah Amanat Bridge Bangladesh"
        ]
    },

    "Central_Railway_Building": {
        "district": "Chattogram",
        "queries": [
            "Central Railway Building Chittagong",
            "Central Railway Building Chattogram",
            "Chittagong Central Railway Building"
        ]
    },

    "Chattogram_Court_Building": {
        "district": "Chattogram",
        "queries": [
            "Chittagong Court Building",
            "Chattogram Court Building",
            "Court Building Chittagong Bangladesh"
        ]
    },

    "Cheragi_Pahar": {
        "district": "Chattogram",
        "queries": [
            "Cheragi Pahar",
            "Cheragi Pahar Chittagong",
            "Cheragi Pahar Chattogram"
        ]
    },

    "Bayazid_Bostami_Shrine": {
        "district": "Chattogram",
        "queries": [
            "Bayazid Bostami Shrine",
            "Bayazid Bostami Mazar Chittagong",
            "Bayazid Bostami Chattogram"
        ]
    },

    "Chandanpura_Mosque": {
        "district": "Chattogram",
        "queries": [
            "Chandanpura Mosque",
            "Chandanpura Masjid Chittagong",
            "Chandanpura Mosque Bangladesh"
        ]
    },

    "Jamboree_Park": {
        "district": "Chattogram",
        "queries": [
            "Jamboree Park Chittagong",
            "Jamboree Park Chattogram",
            "Jamboree Park Bangladesh"
        ]
    },

    "Ethnological_Museum": {
        "district": "Chattogram",
        "queries": [
            "Ethnological Museum Chittagong",
            "Ethnological Museum Chattogram",
            "Bangladesh Ethnological Museum"
        ]
    },

    "Chattogram_War_Cemetery": {
        "district": "Chattogram",
        "queries": [
            "Chittagong War Cemetery",
            "Chattogram War Cemetery",
            "War Cemetery Chittagong Bangladesh"
        ]
    },

    "Batali_Hill": {
        "district": "Chattogram",
        "queries": [
            "Batali Hill Chittagong",
            "Batali Hill Chattogram",
            "Batali Hill Bangladesh"
        ]
    },

    "Chattogram_Railway_Station": {
        "district": "Chattogram",
        "queries": [
            "Chittagong Railway Station",
            "Chattogram Railway Station",
            "Chittagong Railway Station Bangladesh"
        ]
    },

    "Chattogram_Zoo": {
        "district": "Chattogram",
        "queries": [
            "Chittagong Zoo",
            "Chattogram Zoo",
            "Chittagong Zoological Park"
        ]
    },

    "Anderkilla_Shahi_Jame_Mosque": {
        "district": "Chattogram",
        "queries": [
            "Anderkilla Shahi Jame Mosque",
            "Anderkilla Mosque Chittagong",
            "Anderkilla Shahi Jame Masjid"
        ]
    },

    "Chattogram_Central_Shaheed_Minar": {
        "district": "Chattogram",
        "queries": [
            "Chittagong Shaheed Minar",
            "Chattogram Shaheed Minar",
            "Chittagong Central Shaheed Minar"
        ]
    },


    # ============================================================
    # COXS BAZAR
    # ============================================================

    "Coxs_Bazar_Beach": {
        "district": "Coxs_Bazar",
        "queries": [
            "Cox's Bazar Beach",
            "Coxs Bazar Sea Beach",
            "Cox's Bazar Bangladesh"
        ]
    },

    "Inani_Beach": {
        "district": "Coxs_Bazar",
        "queries": [
            "Inani Beach",
            "Inani Sea Beach",
            "Inani Beach Cox's Bazar"
        ]
    },

    "Himchari": {
        "district": "Coxs_Bazar",
        "queries": [
            "Himchari National Park",
            "Himchari Cox's Bazar",
            "Himchari Bangladesh"
        ]
    },

    "Maheshkhali": {
        "district": "Coxs_Bazar",
        "queries": [
            "Maheshkhali Island",
            "Maheshkhali Cox's Bazar",
            "Maheshkhali Bangladesh"
        ]
    },

    "Adinath_Temple": {
        "district": "Coxs_Bazar",
        "queries": [
            "Adinath Temple Maheshkhali",
            "Adinath Mandir Maheshkhali",
            "Adinath Temple Bangladesh"
        ]
    },

    "Sonadia_Island": {
        "district": "Coxs_Bazar",
        "queries": [
            "Sonadia Island",
            "Sonadia Island Bangladesh",
            "Sonadia Cox's Bazar"
        ]
    },

    "Ramu_Buddhist_Temples": {
        "district": "Coxs_Bazar",
        "queries": [
            "Ramu Buddhist Temple",
            "Ramu Buddhist Temples Bangladesh",
            "Ramu Buddhist temple Cox's Bazar"
        ]
    },

    "Dulahazara_Safari_Park": {
        "district": "Coxs_Bazar",
        "queries": [
            "Dulahazara Safari Park",
            "Dulahazara Safari Park Bangladesh",
            "Dulahazara Safari Park Cox's Bazar"
        ]
    },

    "Kutubdia_Island": {
        "district": "Coxs_Bazar",
        "queries": [
            "Kutubdia Island",
            "Kutubdia Bangladesh",
            "Kutubdia Island Cox's Bazar"
        ]
    },

    "Kutubdia_Lighthouse": {
        "district": "Coxs_Bazar",
        "queries": [
            "Kutubdia Lighthouse",
            "Kutubdia Lighthouse Bangladesh",
            "Kutubdia Light House"
        ]
    },

    "Radiant_Fish_World": {
        "district": "Coxs_Bazar",
        "queries": [
            "Radiant Fish World Cox's Bazar",
            "Radiant Fish World Bangladesh",
            "Radiant Fish World"
        ]
    },


    # ============================================================
    # BANDARBAN
    # ============================================================

    "Nilgiri": {
        "district": "Bandarban",
        "queries": [
            "Nilgiri Bandarban",
            "Nilgiri Tourist Center Bandarban",
            "Nilgiri Bangladesh"
        ]
    },

    "Nilachal": {
        "district": "Bandarban",
        "queries": [
            "Nilachal Bandarban",
            "Nilachal Tourist Center",
            "Nilachal Bangladesh"
        ]
    },

    "Boga_Lake": {
        "district": "Bandarban",
        "queries": [
            "Boga Lake Bandarban",
            "Boga Lake Bangladesh",
            "Bogalake Bandarban"
        ]
    },

    "Nafakhum_Waterfall": {
        "district": "Bandarban",
        "queries": [
            "Nafakhum Waterfall",
            "Nafakhum Bandarban",
            "Nafakhum Bangladesh"
        ]
    },

    "Amiakhum": {
        "district": "Bandarban",
        "queries": [
            "Amiakhum Waterfall",
            "Amiakhum Bandarban",
            "Amiakhum Bangladesh"
        ]
    },

    "Keokradong": {
        "district": "Bandarban",
        "queries": [
            "Keokradong",
            "Keokradong Bandarban",
            "Keokradong Bangladesh"
        ]
    },

    "Chimbuk_Hill": {
        "district": "Bandarban",
        "queries": [
            "Chimbuk Hill",
            "Chimbuk Bandarban",
            "Chimbuk Hill Bangladesh"
        ]
    },

    "Meghla_Tourist_Complex": {
        "district": "Bandarban",
        "queries": [
            "Meghla Tourist Complex Bandarban",
            "Meghla Bandarban",
            "Meghla Tourist Center"
        ]
    },

    "Shoilo_Propat": {
        "district": "Bandarban",
        "queries": [
            "Shoilo Propat",
            "Shoilo Propat Bandarban",
            "Shoilo Propat Bangladesh"
        ]
    },

    "Golden_Temple_Bandarban": {
        "district": "Bandarban",
        "queries": [
            "Golden Temple Bandarban",
            "Buddha Dhatu Jadi",
            "Bandarban Golden Temple"
        ]
    },


    # ============================================================
    # RANGAMATI
    # ============================================================

    "Kaptai_Lake": {
        "district": "Rangamati",
        "queries": [
            "Kaptai Lake",
            "Kaptai Lake Rangamati",
            "Kaptai Lake Bangladesh"
        ]
    },

    "Rangamati_Hanging_Bridge": {
        "district": "Rangamati",
        "queries": [
            "Rangamati Hanging Bridge",
            "Rangamati Suspension Bridge",
            "Tourist Hanging Bridge Rangamati"
        ]
    },

    "Shuvolong_Waterfall": {
        "district": "Rangamati",
        "queries": [
            "Shuvolong Waterfall",
            "Shuvolong Rangamati",
            "Shuvolong Bangladesh"
        ]
    },

    "Rajban_Vihara": {
        "district": "Rangamati",
        "queries": [
            "Rajban Vihara",
            "Rajban Bihar Rangamati",
            "Rajban Buddhist Temple"
        ]
    },

    "Wagga_Point": {
        "district": "Rangamati",
        "queries": [
            "Wagga Rangamati",
            "Wagga Tourist Spot",
            "Wagga Point Bangladesh"
        ]
    },

    "Kaptai_Dam": {
        "district": "Rangamati",
        "queries": [
            "Kaptai Dam",
            "Kaptai Dam Bangladesh",
            "Kaptai Hydroelectric Dam"
        ]
    },

    "Peda_Ting_Ting": {
        "district": "Rangamati",
        "queries": [
            "Peda Ting Ting Rangamati",
            "Peda Ting Ting",
            "Peda Ting Ting Bangladesh"
        ]
    },

    "Rangamati_Jum_Museum": {
        "district": "Rangamati",
        "queries": [
            "Jum Museum Rangamati",
            "Rangamati Tribal Museum",
            "Rangamati Jum Museum"
        ]
    },


    # ============================================================
    # KHAGRACHHARI
    # ============================================================

    "Alutila_Cave": {
        "district": "Khagrachhari",
        "queries": [
            "Alutila Cave",
            "Alutila Cave Khagrachhari",
            "Alutila Bangladesh"
        ]
    },

    "Richhang_Waterfall": {
        "district": "Khagrachhari",
        "queries": [
            "Richhang Waterfall",
            "Richhang Jharna Khagrachhari",
            "Richhang Bangladesh"
        ]
    },

    "Nuhang_Jharna": {
        "district": "Khagrachhari",
        "queries": [
            "Nuhang Jharna",
            "Nuhang Waterfall Khagrachhari",
            "Nuhang Bangladesh"
        ]
    },

    "Risang_Waterfall": {
        "district": "Khagrachhari",
        "queries": [
            "Risang Waterfall",
            "Risang Jharna",
            "Risang Khagrachhari"
        ]
    },

    "Alutila_Tunnel": {
        "district": "Khagrachhari",
        "queries": [
            "Alutila Tunnel",
            "Alutila Tunnel Khagrachhari",
            "Alutila Tunnel Bangladesh"
        ]
    },

    "Mong_King_Palace": {
        "district": "Khagrachhari",
        "queries": [
            "Mong King Palace",
            "Mong Circle Palace Khagrachhari",
            "Mong Raja Palace"
        ]
    },


    # ============================================================
    # FENI
    # ============================================================

    "Muhuri_Project": {
        "district": "Feni",
        "queries": [
            "Muhuri Project Feni",
            "Muhuri Project Bangladesh",
            "Muhuri Dam Feni"
        ]
    },

    "Bijoy_Sing_Dighi": {
        "district": "Feni",
        "queries": [
            "Bijoy Sing Dighi",
            "Bijoy Singh Dighi Feni",
            "Bijoy Singh Dighi Bangladesh"
        ]
    },

    "Shamsher_Gazi_Mosque": {
        "district": "Feni",
        "queries": [
            "Shamsher Gazi Mosque",
            "Shamsher Gazi Masjid Feni",
            "Shamsher Gazi Bangladesh"
        ]
    },

    "Rajajhir_Dighi": {
        "district": "Feni",
        "queries": [
            "Rajajhir Dighi Feni",
            "Rajajhir Dighi Bangladesh",
            "Rajajhir Dighi"
        ]
    },


    # ============================================================
    # NOAKHALI
    # ============================================================

    "Nijhum_Dwip": {
        "district": "Noakhali",
        "queries": [
            "Nijhum Dwip",
            "Nijhum Island Bangladesh",
            "Nijhum Dwip Noakhali"
        ]
    },

    "Bajra_Shahi_Mosque": {
        "district": "Noakhali",
        "queries": [
            "Bajra Shahi Mosque",
            "Bajra Mosque Noakhali",
            "Bajra Shahi Masjid"
        ]
    },

    "Noakhali_Jubilee_Park": {
        "district": "Noakhali",
        "queries": [
            "Noakhali Jubilee Park",
            "Jubilee Park Noakhali",
            "Noakhali Jubilee Park Bangladesh"
        ]
    },


    # ============================================================
    # LAKSHMIPUR
    # ============================================================

    "Dalal_Bazar_Jamindar_Bari": {
        "district": "Lakshmipur",
        "queries": [
            "Dalal Bazar Zamindar Bari",
            "Dalal Bazar Jamindar Bari",
            "Dalal Bazar Lakshmipur"
        ]
    },

    "Kamalnagar_Coast": {
        "district": "Lakshmipur",
        "queries": [
            "Kamalnagar Lakshmipur",
            "Kamalnagar coast Bangladesh",
            "Kamalnagar river Lakshmipur"
        ]
    },

    "Ramgati_Beach": {
        "district": "Lakshmipur",
        "queries": [
            "Ramgati Beach",
            "Ramgati Lakshmipur",
            "Ramgati Bangladesh"
        ]
    },


    # ============================================================
    # CUMILLA
    # ============================================================

    "Shalban_Vihara": {
        "district": "Cumilla",
        "queries": [
            "Shalban Vihara",
            "Shalban Bihar Mainamati",
            "Shalban Vihara Cumilla"
        ]
    },

    "Mainamati_Museum": {
        "district": "Cumilla",
        "queries": [
            "Mainamati Museum",
            "Mainamati Archaeological Museum",
            "Mainamati Museum Cumilla"
        ]
    },

    "Itakhola_Mura": {
        "district": "Cumilla",
        "queries": [
            "Itakhola Mura",
            "Itakhola Mura Mainamati",
            "Itakhola Mura Cumilla"
        ]
    },

    "Rupban_Mura": {
        "district": "Cumilla",
        "queries": [
            "Rupban Mura",
            "Rupban Mura Mainamati",
            "Rupban Mura Cumilla"
        ]
    },

    "Ananda_Vihara": {
        "district": "Cumilla",
        "queries": [
            "Ananda Vihara Mainamati",
            "Ananda Bihar Cumilla",
            "Ananda Vihara Bangladesh"
        ]
    },

    "Dharmasagar_Dighi": {
        "district": "Cumilla",
        "queries": [
            "Dharmasagar Dighi",
            "Dharmasagar Cumilla",
            "Dharmasagar Lake Cumilla"
        ]
    },

    "Comilla_Cantonment_War_Cemetery": {
        "district": "Cumilla",
        "queries": [
            "Comilla War Cemetery",
            "Cumilla War Cemetery",
            "Mymensingh War Cemetery Comilla"
        ]
    },

    "Lalmai_Hills": {
        "district": "Cumilla",
        "queries": [
            "Lalmai Hills",
            "Lalmai Hill Cumilla",
            "Lalmai Bangladesh"
        ]
    },


    # ============================================================
    # CHANDPUR
    # ============================================================

    "Three_Rivers_Mouth": {
        "district": "Chandpur",
        "queries": [
            "Three Rivers Mouth Chandpur",
            "Mohanay Chandpur",
            "Chandpur Three Rivers"
        ]
    },

    "Chandpur_Boro_Station": {
        "district": "Chandpur",
        "queries": [
            "Chandpur Boro Station",
            "Chandpur Railway Station",
            "Chandpur Station Bangladesh"
        ]
    },

    "Rupsha_Jamidar_Bari": {
        "district": "Chandpur",
        "queries": [
            "Rupsha Zamindar Bari Chandpur",
            "Rupsha Jamidar Bari",
            "Rupsha Chandpur"
        ]
    },

    "Chandpur_Stadium": {
        "district": "Chandpur",
        "queries": [
            "Chandpur Stadium",
            "Chandpur Stadium Bangladesh",
            "Chandpur District Stadium"
        ]
    },


    # ============================================================
    # BRAHMANBARIA
    # ============================================================

    "Anderson_Canal": {
        "district": "Brahmanbaria",
        "queries": [
            "Anderson Canal Brahmanbaria",
            "Anderson Canal Bangladesh",
            "Anderson Canal"
        ]
    },

    "Haripur_Barendra_Bari": {
        "district": "Brahmanbaria",
        "queries": [
            "Haripur Barendra Bari",
            "Haripur Zamindar Bari Brahmanbaria",
            "Haripur Bangladesh palace"
        ]
    },

    "Arifail_Mosque": {
        "district": "Brahmanbaria",
        "queries": [
            "Arifail Mosque",
            "Arifail Jame Mosque",
            "Arifail Mosque Brahmanbaria"
        ]
    },

    "Uttara_Amar_Dham": {
        "district": "Brahmanbaria",
        "queries": [
            "Uttara Amar Dham",
            "Uttara Amar Dham Brahmanbaria",
            "Amar Dham Bangladesh"
        ]
    },

    "Titas_River": {
        "district": "Brahmanbaria",
        "queries": [
            "Titas River Brahmanbaria",
            "Titas River Bangladesh",
            "Titas River"
        ]
    }
}

print("Total candidate landmarks:", len(LANDMARKS))

Total candidate landmarks: 85

In [ ]:
import json

inventory_file = BASE / "01_inventory" / "landmarks.json"

with open(inventory_file, "w", encoding="utf-8") as f:
    json.dump(LANDMARKS, f, indent=2, ensure_ascii=False)

print("Saved:")
print(inventory_file)

Saved:
/content/drive/MyDrive/Chattogram_Landmark_Dataset/01_inventory/landmarks.json

In [ ]:
from collections import Counter
import pandas as pd

district_counts = Counter(
    info["district"]
    for info in LANDMARKS.values()
)

df_districts = pd.DataFrame(
    district_counts.items(),
    columns=["district", "candidate_landmarks"]
).sort_values(
    "candidate_landmarks",
    ascending=False
)

display(df_districts)

        district  candidate_landmarks
0     Chattogram                   23
1     Coxs_Bazar                   11
2      Bandarban                   10
3      Rangamati                    8
8        Cumilla                    8
4   Khagrachhari                    6
10  Brahmanbaria                    5
9       Chandpur                    4
5           Feni                    4
6       Noakhali                    3
7     Lakshmipur                    3

In [ ]:
import requests
import time
import json
import pandas as pd
from pathlib import Path

API_URL = "https://commons.wikimedia.org/w/api.php"

HEADERS = {
    "User-Agent": (
        "ChattogramDivisionLandmarkDataset/1.0 "
        "(research dataset collection; educational use)"
    )
}

session = requests.Session()
session.headers.update(HEADERS)

CACHE_DIR = BASE / "07_cache" / "wikimedia_scan"
CACHE_DIR.mkdir(parents=True, exist_ok=True)

print("Wikimedia scanner ready.")

Wikimedia scanner ready.

In [ ]:
def wikimedia_request(params, max_retries=6):
    """
    Make a Wikimedia API request with exponential backoff.
    Handles rate limits and temporary server errors.
    """

    delay = 2

    for attempt in range(max_retries):

        try:
            response = session.get(
                API_URL,
                params=params,
                timeout=60
            )

            if response.status_code == 200:
                return response.json()

            if response.status_code in [429, 500, 502, 503, 504]:
                print(
                    f"Temporary HTTP {response.status_code}. "
                    f"Waiting {delay}s..."
                )
                time.sleep(delay)
                delay *= 2
                continue

            response.raise_for_status()

        except requests.RequestException as e:

            print(
                f"Request error: {e}. "
                f"Waiting {delay}s..."
            )

            time.sleep(delay)
            delay *= 2

    raise RuntimeError(
        "Wikimedia request failed after retries."
    )

In [ ]:
def search_commons(query, max_results=200):
    """
    Search Wikimedia Commons for image files.

    Returns:
        {
            "total_hits": ...,
            "files": [...]
        }
    """

    files = {}
    total_hits = None
    continue_params = {}

    while len(files) < max_results:

        params = {
            "action": "query",
            "generator": "search",
            "gsrsearch": query,
            "gsrnamespace": 6,
            "gsrlimit": 50,

            "prop": "imageinfo",
            "iiprop": "url|size|mime|extmetadata",
            "iiurlwidth": 1200,

            "format": "json",
            "formatversion": 2
        }

        params.update(continue_params)

        data = wikimedia_request(params)

        if total_hits is None:
            total_hits = (
                data.get("query", {})
                    .get("searchinfo", {})
                    .get("totalhits")
            )

        pages = (
            data.get("query", {})
                .get("pages", [])
        )

        if not pages:
            break

        for page in pages:

            page_id = page.get("pageid")

            if page_id is not None:
                files[page_id] = page

            if len(files) >= max_results:
                break

        if "continue" not in data:
            break

        continue_params = data["continue"]

        time.sleep(1.5)

    return {
        "total_hits": total_hits or 0,
        "files": list(files.values())
    }

In [ ]:
def scan_landmark(landmark, info):

    cache_file = CACHE_DIR / f"{landmark}.json"

    # Use cached result if available
    if cache_file.exists():

        with open(cache_file, "r", encoding="utf-8") as f:
            return json.load(f)

    all_files = {}

    query_results = []

    for query in info["queries"]:

        print(f"  Searching: {query}")

        try:

            result = search_commons(
                query,
                max_results=200
            )

            query_results.append({
                "query": query,
                "total_hits": result["total_hits"],
                "retrieved": len(result["files"])
            })

            for file in result["files"]:

                pageid = file.get("pageid")

                if pageid:
                    all_files[str(pageid)] = file

        except Exception as e:

            print("  ERROR:", e)

        # Important: slow down requests
        time.sleep(2)

    output = {
        "landmark": landmark,
        "district": info["district"],
        "queries": query_results,
        "unique_files_retrieved": len(all_files),
        "files": list(all_files.values())
    }

    with open(cache_file, "w", encoding="utf-8") as f:
        json.dump(
            output,
            f,
            indent=2,
            ensure_ascii=False
        )

    return output

In [ ]:
availability_rows = []

for i, (landmark, info) in enumerate(LANDMARKS.items(), start=1):

    print("=" * 70)
    print(f"{i}/{len(LANDMARKS)} : {landmark}")

    result = scan_landmark(
        landmark,
        info
    )

    total_hits = sum(
        q["total_hits"]
        for q in result["queries"]
    )

    unique_files = result["unique_files_retrieved"]

    availability_rows.append({
        "landmark": landmark,
        "district": info["district"],
        "query_count": len(info["queries"]),
        "sum_query_hits": total_hits,
        "unique_files_retrieved": unique_files
    })

availability_df = pd.DataFrame(
    availability_rows
)

availability_df = availability_df.sort_values(
    "unique_files_retrieved",
    ascending=False
)

display(availability_df)

======================================================================
1/85 : Patenga_Beach
======================================================================
2/85 : Foys_Lake
======================================================================
3/85 : Parki_Beach
======================================================================
4/85 : Chandranath_Hill
======================================================================
5/85 : Chandranath_Temple
======================================================================
6/85 : Sitakunda_Eco_Park
======================================================================
7/85 : Guliakhali_Beach
======================================================================
8/85 : Banshbaria_Beach
======================================================================
9/85 : Kalurghat_Bridge
======================================================================
10/85 : Shah_Amanat_Bridge
======================================================================
11/85 : Central_Railway_Building
======================================================================
12/85 : Chattogram_Court_Building
  Searching: Chittagong Court Building
  Searching: Chattogram Court Building
  Searching: Court Building Chittagong Bangladesh
======================================================================
13/85 : Cheragi_Pahar
  Searching: Cheragi Pahar
  Searching: Cheragi Pahar Chittagong
  Searching: Cheragi Pahar Chattogram
======================================================================
14/85 : Bayazid_Bostami_Shrine
  Searching: Bayazid Bostami Shrine
  Searching: Bayazid Bostami Mazar Chittagong
  Searching: Bayazid Bostami Chattogram
======================================================================
15/85 : Chandanpura_Mosque
  Searching: Chandanpura Mosque
  Searching: Chandanpura Masjid Chittagong
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Chandanpura Mosque Bangladesh
======================================================================
16/85 : Jamboree_Park
  Searching: Jamboree Park Chittagong
  Searching: Jamboree Park Chattogram
  Searching: Jamboree Park Bangladesh
======================================================================
17/85 : Ethnological_Museum
  Searching: Ethnological Museum Chittagong
  Searching: Ethnological Museum Chattogram
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Bangladesh Ethnological Museum
======================================================================
18/85 : Chattogram_War_Cemetery
  Searching: Chittagong War Cemetery
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Chattogram War Cemetery
  Searching: War Cemetery Chittagong Bangladesh
======================================================================
19/85 : Batali_Hill
  Searching: Batali Hill Chittagong
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Batali Hill Chattogram
  Searching: Batali Hill Bangladesh
======================================================================
20/85 : Chattogram_Railway_Station
  Searching: Chittagong Railway Station
  Searching: Chattogram Railway Station
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
  Searching: Chittagong Railway Station Bangladesh
======================================================================
21/85 : Chattogram_Zoo
  Searching: Chittagong Zoo
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Chattogram Zoo
  Searching: Chittagong Zoological Park
======================================================================
22/85 : Anderkilla_Shahi_Jame_Mosque
  Searching: Anderkilla Shahi Jame Mosque
  Searching: Anderkilla Mosque Chittagong
  Searching: Anderkilla Shahi Jame Masjid
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
======================================================================
23/85 : Chattogram_Central_Shaheed_Minar
  Searching: Chittagong Shaheed Minar
  Searching: Chattogram Shaheed Minar
  Searching: Chittagong Central Shaheed Minar
======================================================================
24/85 : Coxs_Bazar_Beach
  Searching: Cox's Bazar Beach
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Coxs Bazar Sea Beach
  Searching: Cox's Bazar Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
======================================================================
25/85 : Inani_Beach
  Searching: Inani Beach
  Searching: Inani Sea Beach
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
  Searching: Inani Beach Cox's Bazar
======================================================================
26/85 : Himchari
  Searching: Himchari National Park
  Searching: Himchari Cox's Bazar
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Himchari Bangladesh
======================================================================
27/85 : Maheshkhali
  Searching: Maheshkhali Island
  Searching: Maheshkhali Cox's Bazar
  Searching: Maheshkhali Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
======================================================================
28/85 : Adinath_Temple
  Searching: Adinath Temple Maheshkhali
  Searching: Adinath Mandir Maheshkhali
  Searching: Adinath Temple Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
======================================================================
29/85 : Sonadia_Island
  Searching: Sonadia Island
  Searching: Sonadia Island Bangladesh
  Searching: Sonadia Cox's Bazar
======================================================================
30/85 : Ramu_Buddhist_Temples
  Searching: Ramu Buddhist Temple
  Searching: Ramu Buddhist Temples Bangladesh
  Searching: Ramu Buddhist temple Cox's Bazar
======================================================================
31/85 : Dulahazara_Safari_Park
  Searching: Dulahazara Safari Park
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
Temporary HTTP 429. Waiting 32s...
  Searching: Dulahazara Safari Park Bangladesh
  Searching: Dulahazara Safari Park Cox's Bazar
======================================================================
32/85 : Kutubdia_Island
  Searching: Kutubdia Island
  Searching: Kutubdia Bangladesh
  Searching: Kutubdia Island Cox's Bazar
======================================================================
33/85 : Kutubdia_Lighthouse
  Searching: Kutubdia Lighthouse
  Searching: Kutubdia Lighthouse Bangladesh
  Searching: Kutubdia Light House
======================================================================
34/85 : Radiant_Fish_World
  Searching: Radiant Fish World Cox's Bazar
  Searching: Radiant Fish World Bangladesh
  Searching: Radiant Fish World
======================================================================
35/85 : Nilgiri
  Searching: Nilgiri Bandarban
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Nilgiri Tourist Center Bandarban
  Searching: Nilgiri Bangladesh
======================================================================
36/85 : Nilachal
  Searching: Nilachal Bandarban
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Nilachal Tourist Center
  Searching: Nilachal Bangladesh
======================================================================
37/85 : Boga_Lake
  Searching: Boga Lake Bandarban
  Searching: Boga Lake Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Bogalake Bandarban
======================================================================
38/85 : Nafakhum_Waterfall
  Searching: Nafakhum Waterfall
  Searching: Nafakhum Bandarban
  Searching: Nafakhum Bangladesh
======================================================================
39/85 : Amiakhum
  Searching: Amiakhum Waterfall
  Searching: Amiakhum Bandarban
  Searching: Amiakhum Bangladesh
======================================================================
40/85 : Keokradong
  Searching: Keokradong
  Searching: Keokradong Bandarban
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Keokradong Bangladesh
======================================================================
41/85 : Chimbuk_Hill
  Searching: Chimbuk Hill
  Searching: Chimbuk Bandarban
  Searching: Chimbuk Hill Bangladesh
======================================================================
42/85 : Meghla_Tourist_Complex
  Searching: Meghla Tourist Complex Bandarban
  Searching: Meghla Bandarban
  Searching: Meghla Tourist Center
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
======================================================================
43/85 : Shoilo_Propat
  Searching: Shoilo Propat
  Searching: Shoilo Propat Bandarban
  Searching: Shoilo Propat Bangladesh
======================================================================
44/85 : Golden_Temple_Bandarban
  Searching: Golden Temple Bandarban
  Searching: Buddha Dhatu Jadi
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
  Searching: Bandarban Golden Temple
======================================================================
45/85 : Kaptai_Lake
  Searching: Kaptai Lake
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
Temporary HTTP 429. Waiting 32s...
  Searching: Kaptai Lake Rangamati
  Searching: Kaptai Lake Bangladesh
======================================================================
46/85 : Rangamati_Hanging_Bridge
  Searching: Rangamati Hanging Bridge
  Searching: Rangamati Suspension Bridge
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Tourist Hanging Bridge Rangamati
======================================================================
47/85 : Shuvolong_Waterfall
  Searching: Shuvolong Waterfall
  Searching: Shuvolong Rangamati
  Searching: Shuvolong Bangladesh
======================================================================
48/85 : Rajban_Vihara
  Searching: Rajban Vihara
  Searching: Rajban Bihar Rangamati
  Searching: Rajban Buddhist Temple
======================================================================
49/85 : Wagga_Point
  Searching: Wagga Rangamati
  Searching: Wagga Tourist Spot
  Searching: Wagga Point Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
======================================================================
50/85 : Kaptai_Dam
  Searching: Kaptai Dam
  Searching: Kaptai Dam Bangladesh
  Searching: Kaptai Hydroelectric Dam
======================================================================
51/85 : Peda_Ting_Ting
  Searching: Peda Ting Ting Rangamati
  Searching: Peda Ting Ting
  Searching: Peda Ting Ting Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
======================================================================
52/85 : Rangamati_Jum_Museum
  Searching: Jum Museum Rangamati
  Searching: Rangamati Tribal Museum
  Searching: Rangamati Jum Museum
======================================================================
53/85 : Alutila_Cave
  Searching: Alutila Cave
  Searching: Alutila Cave Khagrachhari
  Searching: Alutila Bangladesh
======================================================================
54/85 : Richhang_Waterfall
  Searching: Richhang Waterfall
  Searching: Richhang Jharna Khagrachhari
  Searching: Richhang Bangladesh
======================================================================
55/85 : Nuhang_Jharna
  Searching: Nuhang Jharna
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
Temporary HTTP 429. Waiting 32s...
  Searching: Nuhang Waterfall Khagrachhari
  Searching: Nuhang Bangladesh
======================================================================
56/85 : Risang_Waterfall
  Searching: Risang Waterfall
  Searching: Risang Jharna
  Searching: Risang Khagrachhari
======================================================================
57/85 : Alutila_Tunnel
  Searching: Alutila Tunnel
  Searching: Alutila Tunnel Khagrachhari
  Searching: Alutila Tunnel Bangladesh
======================================================================
58/85 : Mong_King_Palace
  Searching: Mong King Palace
  Searching: Mong Circle Palace Khagrachhari
  Searching: Mong Raja Palace
======================================================================
59/85 : Muhuri_Project
  Searching: Muhuri Project Feni
  Searching: Muhuri Project Bangladesh
  Searching: Muhuri Dam Feni
======================================================================
60/85 : Bijoy_Sing_Dighi
  Searching: Bijoy Sing Dighi
  Searching: Bijoy Singh Dighi Feni
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Bijoy Singh Dighi Bangladesh
======================================================================
61/85 : Shamsher_Gazi_Mosque
  Searching: Shamsher Gazi Mosque
  Searching: Shamsher Gazi Masjid Feni
  Searching: Shamsher Gazi Bangladesh
======================================================================
62/85 : Rajajhir_Dighi
  Searching: Rajajhir Dighi Feni
  Searching: Rajajhir Dighi Bangladesh
  Searching: Rajajhir Dighi
======================================================================
63/85 : Nijhum_Dwip
  Searching: Nijhum Dwip
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Nijhum Island Bangladesh
  Searching: Nijhum Dwip Noakhali
======================================================================
64/85 : Bajra_Shahi_Mosque
  Searching: Bajra Shahi Mosque
  Searching: Bajra Mosque Noakhali
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Bajra Shahi Masjid
======================================================================
65/85 : Noakhali_Jubilee_Park
  Searching: Noakhali Jubilee Park
  Searching: Jubilee Park Noakhali
  Searching: Noakhali Jubilee Park Bangladesh
======================================================================
66/85 : Dalal_Bazar_Jamindar_Bari
  Searching: Dalal Bazar Zamindar Bari
  Searching: Dalal Bazar Jamindar Bari
  Searching: Dalal Bazar Lakshmipur
======================================================================
67/85 : Kamalnagar_Coast
  Searching: Kamalnagar Lakshmipur
  Searching: Kamalnagar coast Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Kamalnagar river Lakshmipur
======================================================================
68/85 : Ramgati_Beach
  Searching: Ramgati Beach
  Searching: Ramgati Lakshmipur
  Searching: Ramgati Bangladesh
======================================================================
69/85 : Shalban_Vihara
  Searching: Shalban Vihara
  Searching: Shalban Bihar Mainamati
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
  Searching: Shalban Vihara Cumilla
======================================================================
70/85 : Mainamati_Museum
  Searching: Mainamati Museum
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
Temporary HTTP 429. Waiting 32s...
  Searching: Mainamati Archaeological Museum
  Searching: Mainamati Museum Cumilla
======================================================================
71/85 : Itakhola_Mura
  Searching: Itakhola Mura
  Searching: Itakhola Mura Mainamati
  Searching: Itakhola Mura Cumilla
======================================================================
72/85 : Rupban_Mura
  Searching: Rupban Mura
  Searching: Rupban Mura Mainamati
  Searching: Rupban Mura Cumilla
======================================================================
73/85 : Ananda_Vihara
  Searching: Ananda Vihara Mainamati
  Searching: Ananda Bihar Cumilla
  Searching: Ananda Vihara Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
Temporary HTTP 429. Waiting 32s...
======================================================================
74/85 : Dharmasagar_Dighi
  Searching: Dharmasagar Dighi
  Searching: Dharmasagar Cumilla
  Searching: Dharmasagar Lake Cumilla
======================================================================
75/85 : Comilla_Cantonment_War_Cemetery
  Searching: Comilla War Cemetery
  Searching: Cumilla War Cemetery
  Searching: Mymensingh War Cemetery Comilla
Temporary HTTP 429. Waiting 2s...
======================================================================
76/85 : Lalmai_Hills
  Searching: Lalmai Hills
  Searching: Lalmai Hill Cumilla
  Searching: Lalmai Bangladesh
======================================================================
77/85 : Three_Rivers_Mouth
  Searching: Three Rivers Mouth Chandpur
  Searching: Mohanay Chandpur
  Searching: Chandpur Three Rivers
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
======================================================================
78/85 : Chandpur_Boro_Station
  Searching: Chandpur Boro Station
  Searching: Chandpur Railway Station
  Searching: Chandpur Station Bangladesh
======================================================================
79/85 : Rupsha_Jamidar_Bari
  Searching: Rupsha Zamindar Bari Chandpur
  Searching: Rupsha Jamidar Bari
  Searching: Rupsha Chandpur
======================================================================
80/85 : Chandpur_Stadium
  Searching: Chandpur Stadium
  Searching: Chandpur Stadium Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
  Searching: Chandpur District Stadium
======================================================================
81/85 : Anderson_Canal
  Searching: Anderson Canal Brahmanbaria
  Searching: Anderson Canal Bangladesh
  Searching: Anderson Canal
======================================================================
82/85 : Haripur_Barendra_Bari
  Searching: Haripur Barendra Bari

,landmark,district,query_count,sum_query_hits,unique_files_retrieved
23,Coxs_Bazar_Beach,Coxs_Bazar,3,0,410
44,Kaptai_Lake,Rangamati,3,0,352
19,Chattogram_Railway_Station,Chattogram,3,0,343
0,Patenga_Beach,Chattogram,3,0,307
34,Nilgiri,Bandarban,3,0,301
...,...,...,...,...,...
54,Nuhang_Jharna,Khagrachhari,3,0,0
61,Rajajhir_Dighi,Feni,3,0,0
64,Noakhali_Jubilee_Park,Noakhali,3,0,0
53,Richhang_Waterfall,Khagrachhari,3,0,0
83,Uttara_Amar_Dham,Brahmanbaria,3,0,0

In [ ]:
availability_file = (
    BASE /
    "02_availability" /
    "availability_report.csv"
)

availability_df.to_csv(
    availability_file,
    index=False
)

print("Saved:")
print(availability_file)

Saved:
/content/drive/MyDrive/Chattogram_Landmark_Dataset/02_availability/availability_report.csv

In [ ]:
def availability_status(n):

    if n >= 100:
        return "STRONG"

    elif n >= 60:
        return "GOOD"

    elif n >= 40:
        return "MODERATE"

    elif n >= 20:
        return "WEAK"

    elif n > 0:
        return "VERY_WEAK"

    else:
        return "RECHECK"


availability_df["status"] = (
    availability_df["unique_files_retrieved"]
    .apply(availability_status)
)

display(
    availability_df[
        [
            "landmark",
            "district",
            "unique_files_retrieved",
            "status"
        ]
    ]
)

                      landmark      district  unique_files_retrieved   status
23            Coxs_Bazar_Beach    Coxs_Bazar                     410   STRONG
44                 Kaptai_Lake     Rangamati                     352   STRONG
19  Chattogram_Railway_Station    Chattogram                     343   STRONG
0                Patenga_Beach    Chattogram                     307   STRONG
34                     Nilgiri     Bandarban                     301   STRONG
..                         ...           ...                     ...      ...
54               Nuhang_Jharna  Khagrachhari                       0  RECHECK
61              Rajajhir_Dighi          Feni                       0  RECHECK
64       Noakhali_Jubilee_Park      Noakhali                       0  RECHECK
53          Richhang_Waterfall  Khagrachhari                       0  RECHECK
83            Uttara_Amar_Dham  Brahmanbaria                       0  RECHECK

[85 rows x 4 columns]

In [ ]:
district_summary = (
    availability_df
    .groupby("district")
    .agg(
        candidate_count=("landmark", "count"),
        total_available=("unique_files_retrieved", "sum"),
        median_available=("unique_files_retrieved", "median")
    )
    .reset_index()
)

display(district_summary)

        district  candidate_count  total_available  median_available
0      Bandarban               10              972              67.0
1   Brahmanbaria                5              573             119.0
2       Chandpur                4              154              34.0
3     Chattogram               23             3643             121.0
4     Coxs_Bazar               11             1789             202.0
5        Cumilla                8             1075             135.0
6           Feni                4               23               4.0
7   Khagrachhari                6              289              12.5
8     Lakshmipur                3              139              50.0
9       Noakhali                3              245              36.0
10     Rangamati                8              849              32.5

In [ ]:
weak_df = availability_df[
    availability_df["status"].isin(
        ["VERY_WEAK", "RECHECK"]
    )
].copy()

display(
    weak_df[
        [
            "landmark",
            "district",
            "unique_files_retrieved",
            "status"
        ]
    ]
)

                 landmark      district  unique_files_retrieved     status
38               Amiakhum     Bandarban                      19  VERY_WEAK
58         Muhuri_Project          Feni                      15  VERY_WEAK
51   Rangamati_Jum_Museum     Rangamati                      13  VERY_WEAK
47          Rajban_Vihara     Rangamati                      11  VERY_WEAK
48            Wagga_Point     Rangamati                       7  VERY_WEAK
66       Kamalnagar_Coast    Lakshmipur                       6  VERY_WEAK
60   Shamsher_Gazi_Mosque          Feni                       6  VERY_WEAK
42          Shoilo_Propat     Bandarban                       5  VERY_WEAK
72          Ananda_Vihara       Cumilla                       4  VERY_WEAK
59       Bijoy_Sing_Dighi          Feni                       2  VERY_WEAK
56         Alutila_Tunnel  Khagrachhari                       1  VERY_WEAK
54          Nuhang_Jharna  Khagrachhari                       0    RECHECK
61         Rajajhir_Dighi          Feni                       0    RECHECK
64  Noakhali_Jubilee_Park      Noakhali                       0    RECHECK
53     Richhang_Waterfall  Khagrachhari                       0    RECHECK
83       Uttara_Amar_Dham  Brahmanbaria                       0    RECHECK

In [ ]:
# Search ONLY weak/recheck classes again.
# This avoids repeatedly querying strong classes.

for _, row in weak_df.iterrows():

    landmark = row["landmark"]

    print("\nRECHECKING:", landmark)

    info = LANDMARKS[landmark]

    # Delete old cache so we perform a fresh scan
    cache_file = CACHE_DIR / f"{landmark}.json"

    if cache_file.exists():
        cache_file.unlink()

    result = scan_landmark(
        landmark,
        info
    )

    print(
        "Unique files retrieved:",
        result["unique_files_retrieved"]
    )

RECHECKING: Amiakhum
  Searching: Amiakhum Waterfall
  Searching: Amiakhum Bandarban
  Searching: Amiakhum Bangladesh
Unique files retrieved: 19

RECHECKING: Muhuri_Project
  Searching: Muhuri Project Feni
  Searching: Muhuri Project Bangladesh
  Searching: Muhuri Dam Feni
Unique files retrieved: 15

RECHECKING: Rangamati_Jum_Museum
  Searching: Jum Museum Rangamati
  Searching: Rangamati Tribal Museum
  Searching: Rangamati Jum Museum
Unique files retrieved: 13

RECHECKING: Rajban_Vihara
  Searching: Rajban Vihara
  Searching: Rajban Bihar Rangamati
  Searching: Rajban Buddhist Temple
Unique files retrieved: 11

RECHECKING: Wagga_Point
  Searching: Wagga Rangamati
  Searching: Wagga Tourist Spot
  Searching: Wagga Point Bangladesh
Unique files retrieved: 7

RECHECKING: Kamalnagar_Coast
  Searching: Kamalnagar Lakshmipur
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
Temporary HTTP 429. Waiting 32s...
  Searching: Kamalnagar coast Bangladesh
  Searching: Kamalnagar river Lakshmipur
Unique files retrieved: 6

RECHECKING: Shamsher_Gazi_Mosque
  Searching: Shamsher Gazi Mosque
  Searching: Shamsher Gazi Masjid Feni
  Searching: Shamsher Gazi Bangladesh
Unique files retrieved: 6

RECHECKING: Shoilo_Propat
  Searching: Shoilo Propat
  Searching: Shoilo Propat Bandarban
  Searching: Shoilo Propat Bangladesh
Unique files retrieved: 5

RECHECKING: Ananda_Vihara
  Searching: Ananda Vihara Mainamati
  Searching: Ananda Bihar Cumilla
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
  Searching: Ananda Vihara Bangladesh
Unique files retrieved: 4

RECHECKING: Bijoy_Sing_Dighi
  Searching: Bijoy Sing Dighi
  Searching: Bijoy Singh Dighi Feni
  Searching: Bijoy Singh Dighi Bangladesh
Unique files retrieved: 2

RECHECKING: Alutila_Tunnel
  Searching: Alutila Tunnel
  Searching: Alutila Tunnel Khagrachhari
  Searching: Alutila Tunnel Bangladesh
Unique files retrieved: 1

RECHECKING: Nuhang_Jharna
  Searching: Nuhang Jharna
  Searching: Nuhang Waterfall Khagrachhari
  Searching: Nuhang Bangladesh
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
Temporary HTTP 429. Waiting 16s...
Temporary HTTP 429. Waiting 32s...
Unique files retrieved: 0

RECHECKING: Rajajhir_Dighi
  Searching: Rajajhir Dighi Feni
  Searching: Rajajhir Dighi Bangladesh
  Searching: Rajajhir Dighi
Unique files retrieved: 0

RECHECKING: Noakhali_Jubilee_Park
  Searching: Noakhali Jubilee Park
  Searching: Jubilee Park Noakhali
  Searching: Noakhali Jubilee Park Bangladesh
Unique files retrieved: 0

RECHECKING: Richhang_Waterfall
  Searching: Richhang Waterfall
  Searching: Richhang Jharna Khagrachhari
  Searching: Richhang Bangladesh
Unique files retrieved: 0

RECHECKING: Uttara_Amar_Dham
  Searching: Uttara Amar Dham
Temporary HTTP 429. Waiting 2s...
Temporary HTTP 429. Waiting 4s...
Temporary HTTP 429. Waiting 8s...
  Searching: Uttara Amar Dham Brahmanbaria
  Searching: Amar Dham Bangladesh
Unique files retrieved: 0

In [ ]:
CANDIDATE_DIR = BASE / "03_candidates"

for landmark in LANDMARKS:
    (CANDIDATE_DIR / landmark).mkdir(
        parents=True,
        exist_ok=True
    )

print("Candidate directories created.")

Candidate directories created.

In [ ]:
from PIL import Image
from io import BytesIO
import hashlib

MIN_WIDTH = 300
MIN_HEIGHT = 300


def validate_image_bytes(content):

    try:

        image = Image.open(
            BytesIO(content)
        )

        image.verify()

        image = Image.open(
            BytesIO(content)
        )

        width, height = image.size

        if width < MIN_WIDTH or height < MIN_HEIGHT:
            return False, "too_small"

        if image.format not in [
            "JPEG",
            "PNG",
            "WEBP"
        ]:
            return False, "unsupported_format"

        return True, "valid"

    except Exception:
        return False, "corrupt"

In [ ]:
def download_image(url):

    try:

        response = session.get(
            url,
            timeout=60
        )

        if response.status_code != 200:
            return None, f"http_{response.status_code}"

        valid, reason = validate_image_bytes(
            response.content
        )

        if not valid:
            return None, reason

        return response.content, "valid"

    except Exception as e:

        return None, str(e)

In [ ]:
def get_metadata(page):

    imageinfo = (
        page.get("imageinfo", [{}])[0]
    )

    metadata = imageinfo.get(
        "extmetadata",
        {}
    )

    def meta_value(key):

        value = metadata.get(key, {})

        if isinstance(value, dict):
            return value.get("value", "")

        return str(value)

    return {
        "pageid": page.get("pageid"),
        "title": page.get("title", ""),
        "file_url": imageinfo.get("url", ""),
        "thumb_url": imageinfo.get("thumburl", ""),
        "description_url": imageinfo.get("descriptionurl", ""),
        "width": imageinfo.get("width"),
        "height": imageinfo.get("height"),
        "mime": imageinfo.get("mime"),
        "license": meta_value("LicenseShortName"),
        "artist": meta_value("Artist"),
        "credit": meta_value("Credit"),
        "date": meta_value("DateTimeOriginal")
    }

In [ ]:
import re
import pandas as pd
from tqdm.auto import tqdm


def safe_filename(text):

    text = re.sub(
        r"[^A-Za-z0-9._-]+",
        "_",
        text
    )

    return text[:120]


download_records = []


# Maximum candidate images per class
MAX_CANDIDATES = 120


for landmark, info in LANDMARKS.items():

    cache_file = CACHE_DIR / f"{landmark}.json"

    if not cache_file.exists():
        print("Skipping:", landmark)
        continue

    with open(
        cache_file,
        "r",
        encoding="utf-8"
    ) as f:

        scan_data = json.load(f)

    pages = scan_data.get(
        "files",
        []
    )

    if len(pages) == 0:
        continue

    output_dir = (
        CANDIDATE_DIR / landmark
    )

    print(
        f"\n{landmark}: "
        f"{len(pages)} candidate files"
    )

    successful = 0

    seen_sha256 = set()

    for page in tqdm(
        pages[:MAX_CANDIDATES],
        desc=landmark
    ):

        metadata = get_metadata(page)

        url = (
            metadata["thumb_url"]
            or metadata["file_url"]
        )

        if not url:
            continue

        content, status = download_image(url)

        if content is None:
            download_records.append({
                "landmark": landmark,
                "status": status,
                "title": metadata["title"]
            })
            continue

        sha256 = hashlib.sha256(
            content
        ).hexdigest()

        # Exact duplicate
        if sha256 in seen_sha256:
            continue

        seen_sha256.add(sha256)

        filename = (
            f"{successful+1:04d}_"
            f"{safe_filename(metadata['title'])}.jpg"
        )

        filepath = (
            output_dir / filename
        )

        try:

            image = Image.open(
                BytesIO(content)
            ).convert("RGB")

            image.save(
                filepath,
                "JPEG",
                quality=95
            )

            download_records.append({
                "landmark": landmark,
                "district": info["district"],
                "filename": filename,
                "path": str(filepath),
                "sha256": sha256,
                "title": metadata["title"],
                "file_url": metadata["file_url"],
                "description_url": metadata["description_url"],
                "license": metadata["license"],
                "artist": metadata["artist"],
                "width": metadata["width"],
                "height": metadata["height"],
                "status": "downloaded"
            })

            successful += 1

        except Exception as e:

            print(
                "Save error:",
                e
            )

        time.sleep(0.3)

    print(
        "Successfully downloaded:",
        successful
    )

Patenga_Beach: 307 candidate files

Patenga_Beach:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 119

Foys_Lake: 121 candidate files

Foys_Lake:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 85

Parki_Beach: 20 candidate files

Parki_Beach:   0%|          | 0/20 [00:00<?, ?it/s]

Successfully downloaded: 13

Chandranath_Hill: 270 candidate files

Chandranath_Hill:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 101

Chandranath_Temple: 111 candidate files

Chandranath_Temple:   0%|          | 0/111 [00:00<?, ?it/s]

Successfully downloaded: 96

Sitakunda_Eco_Park: 265 candidate files

Sitakunda_Eco_Park:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 114

Guliakhali_Beach: 91 candidate files

Guliakhali_Beach:   0%|          | 0/91 [00:00<?, ?it/s]

Successfully downloaded: 88

Banshbaria_Beach: 59 candidate files

Banshbaria_Beach:   0%|          | 0/59 [00:00<?, ?it/s]

Successfully downloaded: 58

Kalurghat_Bridge: 87 candidate files

Kalurghat_Bridge:   0%|          | 0/87 [00:00<?, ?it/s]

Successfully downloaded: 86

Shah_Amanat_Bridge: 210 candidate files

Shah_Amanat_Bridge:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 64

Central_Railway_Building: 184 candidate files

Central_Railway_Building:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 119

Chattogram_Court_Building: 238 candidate files

Chattogram_Court_Building:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 104

Cheragi_Pahar: 50 candidate files

Cheragi_Pahar:   0%|          | 0/50 [00:00<?, ?it/s]

Successfully downloaded: 38

Bayazid_Bostami_Shrine: 54 candidate files

Bayazid_Bostami_Shrine:   0%|          | 0/54 [00:00<?, ?it/s]

Successfully downloaded: 48

Chandanpura_Mosque: 37 candidate files

Chandanpura_Mosque:   0%|          | 0/37 [00:00<?, ?it/s]

Successfully downloaded: 35

Jamboree_Park: 49 candidate files

Jamboree_Park:   0%|          | 0/49 [00:00<?, ?it/s]

Successfully downloaded: 48

Ethnological_Museum: 212 candidate files

Ethnological_Museum:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 120

Chattogram_War_Cemetery: 202 candidate files

Chattogram_War_Cemetery:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 96

Batali_Hill: 111 candidate files

Batali_Hill:   0%|          | 0/111 [00:00<?, ?it/s]

Successfully downloaded: 111

Chattogram_Railway_Station: 343 candidate files

Chattogram_Railway_Station:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 113

Chattogram_Zoo: 282 candidate files

Chattogram_Zoo:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 118

Anderkilla_Shahi_Jame_Mosque: 97 candidate files

Anderkilla_Shahi_Jame_Mosque:   0%|          | 0/97 [00:00<?, ?it/s]

Successfully downloaded: 86

Chattogram_Central_Shaheed_Minar: 243 candidate files

Chattogram_Central_Shaheed_Minar:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 106

Coxs_Bazar_Beach: 410 candidate files

Coxs_Bazar_Beach:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 110

Inani_Beach: 210 candidate files

Inani_Beach:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 90

Himchari: 258 candidate files

Himchari:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 103

Maheshkhali: 216 candidate files

Maheshkhali:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 113

Adinath_Temple: 207 candidate files

Adinath_Temple:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 117

Sonadia_Island: 20 candidate files

Sonadia_Island:   0%|          | 0/20 [00:00<?, ?it/s]

Successfully downloaded: 19

Ramu_Buddhist_Temples: 20 candidate files

Ramu_Buddhist_Temples:   0%|          | 0/20 [00:00<?, ?it/s]

Successfully downloaded: 17

Dulahazara_Safari_Park: 80 candidate files

Dulahazara_Safari_Park:   0%|          | 0/80 [00:00<?, ?it/s]

Successfully downloaded: 73

Kutubdia_Island: 145 candidate files

Kutubdia_Island:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 116

Kutubdia_Lighthouse: 21 candidate files

Kutubdia_Lighthouse:   0%|          | 0/21 [00:00<?, ?it/s]

Successfully downloaded: 19

Radiant_Fish_World: 202 candidate files

Radiant_Fish_World:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 120

Nilgiri: 301 candidate files

Nilgiri:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 110

Nilachal: 137 candidate files

Nilachal:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 107

Boga_Lake: 111 candidate files

Boga_Lake:   0%|          | 0/111 [00:00<?, ?it/s]

Successfully downloaded: 101

Nafakhum_Waterfall: 20 candidate files

Nafakhum_Waterfall:   0%|          | 0/20 [00:00<?, ?it/s]

Successfully downloaded: 16

Amiakhum: 19 candidate files

Amiakhum:   0%|          | 0/19 [00:00<?, ?it/s]

Successfully downloaded: 18

Keokradong: 50 candidate files

Keokradong:   0%|          | 0/50 [00:00<?, ?it/s]

Successfully downloaded: 39

Chimbuk_Hill: 84 candidate files

Chimbuk_Hill:   0%|          | 0/84 [00:00<?, ?it/s]

Successfully downloaded: 71

Meghla_Tourist_Complex: 36 candidate files

Meghla_Tourist_Complex:   0%|          | 0/36 [00:00<?, ?it/s]

Successfully downloaded: 29

Shoilo_Propat: 5 candidate files

Shoilo_Propat:   0%|          | 0/5 [00:00<?, ?it/s]

Successfully downloaded: 4

Golden_Temple_Bandarban: 209 candidate files

Golden_Temple_Bandarban:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 108

Kaptai_Lake: 352 candidate files

Kaptai_Lake:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 90

Rangamati_Hanging_Bridge: 201 candidate files

Rangamati_Hanging_Bridge:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 98

Shuvolong_Waterfall: 44 candidate files

Shuvolong_Waterfall:   0%|          | 0/44 [00:00<?, ?it/s]

Successfully downloaded: 33

Rajban_Vihara: 11 candidate files

Rajban_Vihara:   0%|          | 0/11 [00:00<?, ?it/s]

Successfully downloaded: 7

Wagga_Point: 7 candidate files

Wagga_Point:   0%|          | 0/7 [00:00<?, ?it/s]

Successfully downloaded: 7

Kaptai_Dam: 21 candidate files

Kaptai_Dam:   0%|          | 0/21 [00:00<?, ?it/s]

Successfully downloaded: 16

Peda_Ting_Ting: 200 candidate files

Peda_Ting_Ting:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 119

Rangamati_Jum_Museum: 13 candidate files

Rangamati_Jum_Museum:   0%|          | 0/13 [00:00<?, ?it/s]

Successfully downloaded: 13

Alutila_Cave: 37 candidate files

Alutila_Cave:   0%|          | 0/37 [00:00<?, ?it/s]

Successfully downloaded: 34

Risang_Waterfall: 24 candidate files

Risang_Waterfall:   0%|          | 0/24 [00:00<?, ?it/s]

Successfully downloaded: 20

Alutila_Tunnel: 1 candidate files

Alutila_Tunnel:   0%|          | 0/1 [00:00<?, ?it/s]

Successfully downloaded: 1

Mong_King_Palace: 227 candidate files

Mong_King_Palace:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 119

Muhuri_Project: 15 candidate files

Muhuri_Project:   0%|          | 0/15 [00:00<?, ?it/s]

Successfully downloaded: 15

Bijoy_Sing_Dighi: 2 candidate files

Bijoy_Sing_Dighi:   0%|          | 0/2 [00:00<?, ?it/s]

Successfully downloaded: 1

Shamsher_Gazi_Mosque: 6 candidate files

Shamsher_Gazi_Mosque:   0%|          | 0/6 [00:00<?, ?it/s]

Successfully downloaded: 2

Nijhum_Dwip: 209 candidate files

Nijhum_Dwip:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 108

Bajra_Shahi_Mosque: 36 candidate files

Bajra_Shahi_Mosque:   0%|          | 0/36 [00:00<?, ?it/s]

Successfully downloaded: 32

Dalal_Bazar_Jamindar_Bari: 83 candidate files

Dalal_Bazar_Jamindar_Bari:   0%|          | 0/83 [00:00<?, ?it/s]

Successfully downloaded: 83

Kamalnagar_Coast: 6 candidate files

Kamalnagar_Coast:   0%|          | 0/6 [00:00<?, ?it/s]

Successfully downloaded: 6

Ramgati_Beach: 50 candidate files

Ramgati_Beach:   0%|          | 0/50 [00:00<?, ?it/s]

Successfully downloaded: 47

Shalban_Vihara: 287 candidate files

Shalban_Vihara:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 117

Mainamati_Museum: 202 candidate files

Mainamati_Museum:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 119

Itakhola_Mura: 112 candidate files

Itakhola_Mura:   0%|          | 0/112 [00:00<?, ?it/s]

Successfully downloaded: 112

Rupban_Mura: 67 candidate files

Rupban_Mura:   0%|          | 0/67 [00:00<?, ?it/s]

Successfully downloaded: 66

Ananda_Vihara: 4 candidate files

Ananda_Vihara:   0%|          | 0/4 [00:00<?, ?it/s]

Successfully downloaded: 3

Dharmasagar_Dighi: 64 candidate files

Dharmasagar_Dighi:   0%|          | 0/64 [00:00<?, ?it/s]

Successfully downloaded: 63

Comilla_Cantonment_War_Cemetery: 158 candidate files

Comilla_Cantonment_War_Cemetery:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 107

Lalmai_Hills: 181 candidate files

Lalmai_Hills:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 117

Three_Rivers_Mouth: 29 candidate files

Three_Rivers_Mouth:   0%|          | 0/29 [00:00<?, ?it/s]

Successfully downloaded: 29

Chandpur_Boro_Station: 39 candidate files

Chandpur_Boro_Station:   0%|          | 0/39 [00:00<?, ?it/s]

Successfully downloaded: 38

Rupsha_Jamidar_Bari: 21 candidate files

Rupsha_Jamidar_Bari:   0%|          | 0/21 [00:00<?, ?it/s]

Successfully downloaded: 21

Chandpur_Stadium: 65 candidate files

Chandpur_Stadium:   0%|          | 0/65 [00:00<?, ?it/s]

Successfully downloaded: 64

Anderson_Canal: 212 candidate files

Anderson_Canal:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 39

Haripur_Barendra_Bari: 119 candidate files

Haripur_Barendra_Bari:   0%|          | 0/119 [00:00<?, ?it/s]

Successfully downloaded: 115

Arifail_Mosque: 38 candidate files

Arifail_Mosque:   0%|          | 0/38 [00:00<?, ?it/s]

Successfully downloaded: 38

Titas_River: 204 candidate files

Titas_River:   0%|          | 0/120 [00:00<?, ?it/s]

Successfully downloaded: 108

In [ ]:
download_df = pd.DataFrame(
    download_records
)

metadata_file = (
    BASE /
    "03_candidates" /
    "candidate_metadata.csv"
)

download_df.to_csv(
    metadata_file,
    index=False
)

print(
    "Saved metadata:",
    metadata_file
)

display(download_df.head())

Saved metadata: /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/candidate_metadata.csv

,landmark,district,filename,path,sha256,title,file_url,description_url,license,artist,width,height,status
0,Patenga_Beach,Chattogram,0001_File_Patenga_beach_Russell_john.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,d3e1b45f79818208231938c1d2abea7634018ce544649b...,File:Patenga beach Russell john.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Pateng...,CC BY-SA 2.0,"<a rel=""nofollow"" class=""external text"" href=""...",1002.0,598.0,downloaded
1,Patenga_Beach,Chattogram,0002_File_Sunset_at_Patenga_beach.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,7dd6206ac89bb6c9bbb6cecc99b118aa32a27e549ea387...,File:Sunset at Patenga beach.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Sunset...,CC BY 2.0,"<a rel=""nofollow"" class=""external text"" href=""...",800.0,800.0,downloaded
2,Patenga_Beach,Chattogram,0003_File_Patenga_Sea_Beach_Chittagong_02.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,5fe8c1110642e971f5bd26a2b3e55c21d18cdf5a4f92cb...,"File:Patenga Sea Beach, Chittagong 02.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Pateng...,CC BY-SA 4.0,"<a href=""//commons.wikimedia.org/wiki/User:Mot...",4608.0,3456.0,downloaded
3,Patenga_Beach,Chattogram,0004_File_Patenga_Sea_Beach_Chittagong_03.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,1c1d2625912c7062eb32d2600735c3c4c916febff3ba58...,"File:Patenga Sea Beach, Chittagong 03.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Pateng...,CC BY-SA 4.0,"<a href=""//commons.wikimedia.org/wiki/User:Mot...",4608.0,3456.0,downloaded
4,Patenga_Beach,Chattogram,0005_File_Patenga_Sea_Beach_Development_Projec...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,7ca2be456eb5e6fc2309a01f1aa7cbfd28f24272630c44...,File:Patenga Sea Beach Development Project fou...,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Pateng...,CC BY-SA 4.0,"<a href=""//commons.wikimedia.org/wiki/User:Mot...",4608.0,3456.0,downloaded

In [ ]:
candidate_counts = (
    download_df[
        download_df["status"] == "downloaded"
    ]
    .groupby(
        ["district", "landmark"]
    )
    .size()
    .reset_index(
        name="downloaded_images"
    )
    .sort_values(
        "downloaded_images",
        ascending=False
    )
)

display(candidate_counts)

        district                  landmark  downloaded_images
49    Coxs_Bazar        Radiant_Fish_World                120
32    Chattogram       Ethnological_Museum                120
22    Chattogram  Central_Railway_Building                119
57       Cumilla          Mainamati_Museum                119
74     Rangamati            Peda_Ting_Ting                119
..           ...                       ...                ...
9      Bandarban             Shoilo_Propat                  4
52       Cumilla             Ananda_Vihara                  3
62          Feni      Shamsher_Gazi_Mosque                  2
60          Feni          Bijoy_Sing_Dighi                  1
64  Khagrachhari            Alutila_Tunnel                  1

[80 rows x 3 columns]

In [ ]:
import imagehash
from PIL import Image


def calculate_phash(path):

    try:

        image = Image.open(path).convert(
            "RGB"
        )

        return str(
            imagehash.phash(image)
        )

    except Exception:
        return None

In [ ]:
phashes = []

for path in tqdm(
    download_df["path"],
    desc="Calculating perceptual hashes"
):

    phashes.append(
        calculate_phash(path)
    )

download_df["phash"] = phashes

download_df.to_csv(
    metadata_file,
    index=False
)

print("pHash calculation complete.")

Calculating perceptual hashes:   0%|          | 0/6104 [00:00<?, ?it/s]

pHash calculation complete.

In [ ]:
def hamming_distance(hash1, hash2):

    return imagehash.hex_to_hash(
        hash1
    ) - imagehash.hex_to_hash(
        hash2
    )

In [ ]:
PHASH_THRESHOLD = 6

In [ ]:
from collections import defaultdict


def remove_near_duplicates(df, threshold=6):

    keep_indices = []

    for landmark, group in df.groupby(
        "landmark"
    ):

        selected_hashes = []

        for idx, row in group.iterrows():

            current_hash = row["phash"]

            if not current_hash:
                continue

            duplicate = False

            for existing_hash in selected_hashes:

                if hamming_distance(
                    current_hash,
                    existing_hash
                ) <= threshold:

                    duplicate = True
                    break

            if not duplicate:

                keep_indices.append(idx)
                selected_hashes.append(
                    current_hash
                )

    return df.loc[
        keep_indices
    ].reset_index(drop=True)


clean_df = remove_near_duplicates(
    download_df,
    threshold=PHASH_THRESHOLD
)

print(
    "Before:",
    len(download_df)
)

print(
    "After pHash deduplication:",
    len(clean_df)
)

Before: 6104
After pHash deduplication: 5340

In [ ]:
before_counts = (
    download_df
    .groupby("landmark")
    .size()
    .rename("before")
)

after_counts = (
    clean_df
    .groupby("landmark")
    .size()
    .rename("after")
)

dedup_report = pd.concat(
    [before_counts, after_counts],
    axis=1
).fillna(0)

dedup_report["removed"] = (
    dedup_report["before"]
    -
    dedup_report["after"]
)

dedup_report = (
    dedup_report
    .reset_index()
    .sort_values(
        "removed",
        ascending=False
    )
)

display(dedup_report)

                     landmark  before  after  removed
6              Anderson_Canal     120     38       82
70         Shah_Amanat_Bridge     120     57       63
33                  Foys_Lake     120     81       39
38                Inani_Beach     120     88       32
44                Kaptai_Lake     120     90       30
..                        ...     ...    ...      ...
29  Dalal_Bazar_Jamindar_Bari      83     83        0
61         Radiant_Fish_World     120    120        0
66       Rangamati_Jum_Museum      13     13        0
69        Rupsha_Jamidar_Bari      21     21        0
79                Wagga_Point       7      7        0

[80 rows x 4 columns]

In [ ]:
clean_metadata_file = (
    BASE /
    "03_candidates" /
    "clean_candidate_metadata.csv"
)

clean_df.to_csv(
    clean_metadata_file,
    index=False
)

print(
    "Saved:",
    clean_metadata_file
)

Saved: /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/clean_candidate_metadata.csv

In [ ]:
import matplotlib.pyplot as plt
import math


REVIEW_DIR = BASE / "04_review"
REVIEW_DIR.mkdir(
    parents=True,
    exist_ok=True
)


def create_contact_sheet(
    landmark,
    df,
    max_images=40,
    columns=5
):

    subset = df[
        df["landmark"] == landmark
    ].head(max_images)

    if len(subset) == 0:
        return

    rows = math.ceil(
        len(subset) / columns
    )

    fig, axes = plt.subplots(
        rows,
        columns,
        figsize=(15, rows * 3)
    )

    axes = (
        axes.flatten()
        if hasattr(axes, "flatten")
        else [axes]
    )

    for ax, (_, row) in zip(
        axes,
        subset.iterrows()
    ):

        try:

            image = Image.open(
                row["path"]
            )

            ax.imshow(image)

            ax.set_title(
                Path(
                    row["path"]
                ).name[:25],
                fontsize=7
            )

        except Exception:

            ax.text(
                0.5,
                0.5,
                "ERROR",
                ha="center",
                va="center"
            )

        ax.axis("off")

    for ax in axes[
        len(subset):
    ]:
        ax.axis("off")

    plt.suptitle(
        landmark,
        fontsize=14
    )

    plt.tight_layout()

    output = (
        REVIEW_DIR /
        f"{landmark}_contact_sheet.jpg"
    )

    plt.savefig(
        output,
        dpi=150,
        bbox_inches="tight"
    )

    plt.close()

    return output