In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

BASE_DIR = "/content/drive/MyDrive/Chattogram_Landmark_Dataset"

print("Project exists:", os.path.exists(BASE_DIR))

print("\nProject folders:")

for item in os.listdir(BASE_DIR):
    print(" -", item)

Project exists: True

Project folders:
 - 01_inventory
 - 02_wikimedia_scan
 - 03_candidate_pool
 - 04_final_dataset
 - 05_reports
 - 02_availability
 - 03_candidates
 - 04_review
 - 05_final_dataset
 - 06_reports
 - 07_cache

In [ ]:
import os

for root, dirs, files in os.walk(BASE_DIR):

    image_count = sum(
        f.lower().endswith(
            (".jpg", ".jpeg", ".png", ".webp")
        )
        for f in files
    )

    if image_count > 0:
        print(
            f"{root}  -->  {image_count} images"
        )

/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Patenga_Beach  -->  119 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Foys_Lake  -->  85 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Parki_Beach  -->  13 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandranath_Hill  -->  101 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandranath_Temple  -->  96 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Sitakunda_Eco_Park  -->  114 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Guliakhali_Beach  -->  88 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Banshbaria_Beach  -->  58 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kalurghat_Bridge  -->  86 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Shah_Amanat_Bridge  -->  64 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Central_Railway_Building  -->  119 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chattogram_Court_Building  -->  104 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Cheragi_Pahar  -->  38 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Bayazid_Bostami_Shrine  -->  48 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandanpura_Mosque  -->  35 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Jamboree_Park  -->  48 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Ethnological_Museum  -->  120 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chattogram_War_Cemetery  -->  96 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Batali_Hill  -->  111 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chattogram_Railway_Station  -->  113 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chattogram_Zoo  -->  118 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Anderkilla_Shahi_Jame_Mosque  -->  86 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chattogram_Central_Shaheed_Minar  -->  106 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Coxs_Bazar_Beach  -->  110 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Inani_Beach  -->  90 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Himchari  -->  103 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Maheshkhali  -->  113 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Adinath_Temple  -->  117 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Sonadia_Island  -->  19 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Ramu_Buddhist_Temples  -->  17 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Dulahazara_Safari_Park  -->  73 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Island  -->  116 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Lighthouse  -->  19 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Radiant_Fish_World  -->  120 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Nilgiri  -->  110 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Nilachal  -->  107 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Boga_Lake  -->  101 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Nafakhum_Waterfall  -->  16 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Amiakhum  -->  18 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Keokradong  -->  39 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chimbuk_Hill  -->  71 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Meghla_Tourist_Complex  -->  29 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Shoilo_Propat  -->  4 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Golden_Temple_Bandarban  -->  108 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kaptai_Lake  -->  90 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Rangamati_Hanging_Bridge  -->  98 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Shuvolong_Waterfall  -->  33 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Rajban_Vihara  -->  7 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Wagga_Point  -->  7 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kaptai_Dam  -->  16 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Peda_Ting_Ting  -->  119 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Rangamati_Jum_Museum  -->  13 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Alutila_Cave  -->  34 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Risang_Waterfall  -->  20 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Alutila_Tunnel  -->  1 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Mong_King_Palace  -->  119 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Muhuri_Project  -->  15 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Bijoy_Sing_Dighi  -->  1 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Shamsher_Gazi_Mosque  -->  2 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Nijhum_Dwip  -->  108 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Bajra_Shahi_Mosque  -->  32 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Dalal_Bazar_Jamindar_Bari  -->  83 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kamalnagar_Coast  -->  6 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Ramgati_Beach  -->  47 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Shalban_Vihara  -->  117 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Mainamati_Museum  -->  119 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Itakhola_Mura  -->  112 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Rupban_Mura  -->  66 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Ananda_Vihara  -->  3 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Dharmasagar_Dighi  -->  63 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Comilla_Cantonment_War_Cemetery  -->  107 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Lalmai_Hills  -->  117 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Three_Rivers_Mouth  -->  29 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandpur_Boro_Station  -->  38 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Rupsha_Jamidar_Bari  -->  21 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandpur_Stadium  -->  64 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Anderson_Canal  -->  39 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Haripur_Barendra_Bari  -->  115 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Arifail_Mosque  -->  38 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Titas_River  -->  108 images
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review  -->  74 images

In [ ]:
import glob

csv_files = glob.glob(
    BASE_DIR + "/**/*.csv",
    recursive=True
)

print("CSV files found:\n")

for f in csv_files:
    print(f)

CSV files found:

/content/drive/MyDrive/Chattogram_Landmark_Dataset/02_availability/availability_report.csv
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/candidate_metadata.csv
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/clean_candidate_metadata.csv
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/recovered_clean_metadata.csv
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis/exact_duplicates.csv
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis/identical_phash_groups.csv
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis/near_duplicate_pairs.csv

In [ ]:
import pandas as pd
import os

CLEAN_METADATA = (
    "/content/drive/MyDrive/"
    "Chattogram_Landmark_Dataset/"
    "03_candidates/"
    "clean_candidate_metadata.csv"
)

clean_df = pd.read_csv(CLEAN_METADATA)

print("Clean metadata loaded successfully!")
print("Number of records:", len(clean_df))
print("Columns:")
print(clean_df.columns.tolist())

Clean metadata loaded successfully!
Number of records: 5340
Columns:
['landmark', 'district', 'filename', 'path', 'sha256', 'title', 'file_url', 'description_url', 'license', 'artist', 'width', 'height', 'status', 'phash']

In [ ]:
print("Total records:", len(clean_df))
print("Unique landmarks:", clean_df["landmark"].nunique())

print("\nMissing values:")
print(clean_df.isna().sum())

print("\nStatus distribution:")
print(clean_df["status"].value_counts(dropna=False))

print("\nMissing pHash:")
print(clean_df["phash"].isna().sum())

print("\nMissing SHA-256:")
print(clean_df["sha256"].isna().sum())

Total records: 5340
Unique landmarks: 80

Missing values:
landmark            0
district            0
filename            0
path                0
sha256              0
title               0
file_url            0
description_url     0
license             0
artist             82
width               0
height              0
status              0
phash               0
dtype: int64

Status distribution:
status
downloaded    5340
Name: count, dtype: int64

Missing pHash:
0

Missing SHA-256:
0

In [ ]:
import os

clean_df["file_exists"] = clean_df["path"].apply(os.path.exists)

print("Total records:", len(clean_df))
print("Images found:", clean_df["file_exists"].sum())
print("Images missing:", (~clean_df["file_exists"]).sum())

Total records: 5340
Images found: 5340
Images missing: 0

In [ ]:
class_counts = (
    clean_df
    .groupby(["district", "landmark"])
    .size()
    .reset_index(name="image_count")
    .sort_values("image_count", ascending=False)
)

print(class_counts.to_string(index=False))

    district                         landmark  image_count
  Coxs_Bazar               Radiant_Fish_World          120
  Chattogram                    Patenga_Beach          119
  Chattogram              Ethnological_Museum          119
     Cumilla                 Mainamati_Museum          118
  Coxs_Bazar                   Adinath_Temple          117
  Chattogram         Central_Railway_Building          116
     Cumilla                     Lalmai_Hills          116
Khagrachhari                 Mong_King_Palace          116
Brahmanbaria            Haripur_Barendra_Bari          115
  Chattogram                   Chattogram_Zoo          115
  Chattogram               Sitakunda_Eco_Park          114
  Coxs_Bazar                      Maheshkhali          113
     Cumilla                    Itakhola_Mura          112
  Chattogram       Chattogram_Railway_Station          111
     Cumilla                   Shalban_Vihara          110
   Bandarban                          Nilgiri          110
  Coxs_Bazar                 Coxs_Bazar_Beach          110
  Coxs_Bazar                  Kutubdia_Island          109
    Noakhali                      Nijhum_Dwip          108
  Chattogram                      Batali_Hill          107
     Cumilla  Comilla_Cantonment_War_Cemetery          107
   Bandarban          Golden_Temple_Bandarban          107
   Bandarban                         Nilachal          105
Brahmanbaria                      Titas_River          105
  Chattogram        Chattogram_Court_Building          104
  Chattogram Chattogram_Central_Shaheed_Minar          104
   Rangamati                   Peda_Ting_Ting          103
  Coxs_Bazar                         Himchari          102
   Bandarban                        Boga_Lake          101
  Chattogram                 Chandranath_Hill          101
   Rangamati         Rangamati_Hanging_Bridge           98
  Chattogram          Chattogram_War_Cemetery           96
  Chattogram               Chandranath_Temple           94
   Rangamati                      Kaptai_Lake           90
  Coxs_Bazar                      Inani_Beach           88
  Chattogram                 Guliakhali_Beach           87
  Chattogram     Anderkilla_Shahi_Jame_Mosque           86
  Chattogram                 Kalurghat_Bridge           83
  Lakshmipur        Dalal_Bazar_Jamindar_Bari           83
  Chattogram                        Foys_Lake           81
  Coxs_Bazar           Dulahazara_Safari_Park           73
   Bandarban                     Chimbuk_Hill           71
     Cumilla                      Rupban_Mura           66
     Cumilla                Dharmasagar_Dighi           63
  Chattogram               Shah_Amanat_Bridge           57
    Chandpur                 Chandpur_Stadium           53
  Chattogram           Bayazid_Bostami_Shrine           48
  Chattogram                    Jamboree_Park           47
  Chattogram                 Banshbaria_Beach           44
  Lakshmipur                    Ramgati_Beach           39
   Bandarban                       Keokradong           39
Brahmanbaria                   Anderson_Canal           38
  Chattogram                    Cheragi_Pahar           37
  Chattogram               Chandanpura_Mosque           35
Khagrachhari                     Alutila_Cave           34
    Chandpur            Chandpur_Boro_Station           34
    Noakhali               Bajra_Shahi_Mosque           32
Brahmanbaria                   Arifail_Mosque           31
   Rangamati              Shuvolong_Waterfall           31
   Bandarban           Meghla_Tourist_Complex           29
    Chandpur               Three_Rivers_Mouth           28
    Chandpur              Rupsha_Jamidar_Bari           21
Khagrachhari                 Risang_Waterfall           20
  Coxs_Bazar                   Sonadia_Island           18
  Coxs_Bazar              Kutubdia_Lighthouse           18
  Coxs_Bazar            Ramu_Buddhist_Temples           17
   Bandarban                         Amiakhum           17
   Bandarban               Nafakhum_Waterfall           16
   Rangamati                       Kaptai_Dam           15
        Feni                   Muhuri_Project           14
   Rangamati             Rangamati_Jum_Museum           13
  Chattogram                      Parki_Beach           12
   Rangamati                      Wagga_Point            7
   Rangamati                    Rajban_Vihara            7
  Lakshmipur                 Kamalnagar_Coast            5
   Bandarban                    Shoilo_Propat            4
     Cumilla                    Ananda_Vihara            3
        Feni             Shamsher_Gazi_Mosque            2
        Feni                 Bijoy_Sing_Dighi            1
Khagrachhari                   Alutila_Tunnel            1

In [ ]:
targets = [100, 90, 80, 70, 60, 50, 40, 30, 20]

for target in targets:
    n_classes = (
        class_counts["image_count"] >= target
    ).sum()

    print(
        f"{target:3d} images/class -> "
        f"{n_classes:3d} classes"
    )

100 images/class ->  30 classes
 90 images/class ->  34 classes
 80 images/class ->  40 classes
 70 images/class ->  42 classes
 60 images/class ->  44 classes
 50 images/class ->  46 classes
 40 images/class ->  49 classes
 30 images/class ->  59 classes
 20 images/class ->  63 classes

In [ ]:
district_summary = (
    class_counts
    .groupby("district")
    .agg(
        number_of_classes=("landmark", "count"),
        total_images=("image_count", "sum")
    )
    .sort_values(
        "number_of_classes",
        ascending=False
    )
)

district_summary

              number_of_classes  total_images
district
Chattogram                   23          1917
Coxs_Bazar                   11           885
Bandarban                    10           599
Cumilla                       8           695
Rangamati                     8           364
Chandpur                      4           136
Brahmanbaria                  4           289
Khagrachhari                  4           171
Feni                          3            17
Lakshmipur                    3           127
Noakhali                      2           140

In [ ]:
print(
    class_counts
    .groupby("district")["landmark"]
    .count()
)

district
Bandarban       10
Brahmanbaria     4
Chandpur         4
Chattogram      23
Coxs_Bazar      11
Cumilla          8
Feni             3
Khagrachhari     4
Lakshmipur       3
Noakhali         2
Rangamati        8
Name: landmark, dtype: int64

In [ ]:
print(
    class_counts[
        class_counts["image_count"] < 40
    ].to_string(index=False)
)

    district               landmark  image_count
  Lakshmipur          Ramgati_Beach           39
   Bandarban             Keokradong           39
Brahmanbaria         Anderson_Canal           38
  Chattogram          Cheragi_Pahar           37
  Chattogram     Chandanpura_Mosque           35
Khagrachhari           Alutila_Cave           34
    Chandpur  Chandpur_Boro_Station           34
    Noakhali     Bajra_Shahi_Mosque           32
Brahmanbaria         Arifail_Mosque           31
   Rangamati    Shuvolong_Waterfall           31
   Bandarban Meghla_Tourist_Complex           29
    Chandpur     Three_Rivers_Mouth           28
    Chandpur    Rupsha_Jamidar_Bari           21
Khagrachhari       Risang_Waterfall           20
  Coxs_Bazar         Sonadia_Island           18
  Coxs_Bazar    Kutubdia_Lighthouse           18
  Coxs_Bazar  Ramu_Buddhist_Temples           17
   Bandarban               Amiakhum           17
   Bandarban     Nafakhum_Waterfall           16
   Rangamati             Kaptai_Dam           15
        Feni         Muhuri_Project           14
   Rangamati   Rangamati_Jum_Museum           13
  Chattogram            Parki_Beach           12
   Rangamati            Wagga_Point            7
   Rangamati          Rajban_Vihara            7
  Lakshmipur       Kamalnagar_Coast            5
   Bandarban          Shoilo_Propat            4
     Cumilla          Ananda_Vihara            3
        Feni   Shamsher_Gazi_Mosque            2
        Feni       Bijoy_Sing_Dighi            1
Khagrachhari         Alutila_Tunnel            1

In [ ]:
print(
    clean_df["phash"]
    .dropna()
    .head(20)
)

0     d2cc2d36737c3283
1     ca28306fd37b348b
2     861877c2bdf22d19
3     85c3e2bc6c50ee93
4     fed54a9a9472829c
5     879de58ac91af454
6     aaf5b5a4cc532a4a
7     e2ecd78d94945cb0
8     d35d7cf221c85b82
9     d9dad8dbc3f29200
10    dc2baf74825bb520
11    e7c4c1f0f2f13c18
12    d568c832871d0fee
13    81a134b7926f9c7a
14    e1c58f2f92661635
15    8c1db9976b81f981
16    cd85f240607c7ab7
17    a1827d0db0fa9de1
18    d0ff01af5f20de20
19    a89517e65db80d8b
Name: phash, dtype: object

In [ ]:
print(
    "Unique pHash values:",
    clean_df["phash"].nunique()
)

print(
    "Total images:",
    len(clean_df)
)

Unique pHash values: 5132
Total images: 5340

In [ ]:
exact_duplicates = clean_df[
    clean_df.duplicated(
        subset=["sha256"],
        keep=False
    )
].sort_values("sha256")

print(
    "Records involved in exact duplicates:",
    len(exact_duplicates)
)

Records involved in exact duplicates: 398

In [ ]:
print(
    exact_duplicates[
        [
            "landmark",
            "filename",
            "sha256"
        ]
    ].head(30)
)

                             landmark  \
113                    Adinath_Temple
3588                      Maheshkhali
1749  Comilla_Cantonment_War_Cemetery
3667                 Mainamati_Museum
104                    Adinath_Temple
3575                      Maheshkhali
1065               Chandranath_Temple
942                  Chandranath_Hill
1757  Comilla_Cantonment_War_Cemetery
3672                 Mainamati_Museum
1820  Comilla_Cantonment_War_Cemetery
3709                 Mainamati_Museum
1741  Comilla_Cantonment_War_Cemetery
3712                 Mainamati_Museum
3589                      Maheshkhali
71                     Adinath_Temple
3530                      Maheshkhali
29                     Adinath_Temple
1776  Comilla_Cantonment_War_Cemetery
3685                 Mainamati_Museum
3759           Meghla_Tourist_Complex
896                  Chandpur_Stadium
843             Chandpur_Boro_Station
3719                 Mainamati_Museum
1750  Comilla_Cantonment_War_Cemetery
3730                 Mainamati_Museum
1797  Comilla_Cantonment_War_Cemetery
5217               Three_Rivers_Mouth
5031             Shamsher_Gazi_Mosque
832             Chandpur_Boro_Station

                                               filename  \
113                                  0114_File_.jpg.jpg
3588                                 0089_File_.jpg.jpg
1749  0019_File_Mainamati_War_Cemetery_in_2022.03.jp...
3667  0056_File_Mainamati_War_Cemetery_in_2022.03.jp...
104                                  0105_File_.jpg.jpg
3575                                 0076_File_.jpg.jpg
1065                       0068_File_DSC_0244-5.jpg.jpg
942                        0045_File_DSC_0244-5.jpg.jpg
1757  0027_File_Mainamati_War_Cemetery_in_2022.14.jp...
3672  0061_File_Mainamati_War_Cemetery_in_2022.14.jp...
1820  0090_File_The_Mainamati_War_Cemetery_grave_sol...
3709  0098_File_The_Mainamati_War_Cemetery_grave_sol...
1741  0011_File_Mainamati_War_Cemetery_2018-01-09_1_...
3712  0101_File_Mainamati_War_Cemetery_2018-01-09_1_...
3589                                 0090_File_.jpg.jpg
71                                   0072_File_.jpg.jpg
3530  0031_File_Adi_Nath_temple_tree_Moheshkhali.jpg...
29    0030_File_Adi_Nath_temple_tree_Moheshkhali.jpg...
1776  0046_File_Mainamati_War_Cemetery_in_2022.42.jp...
3685  0074_File_Mainamati_War_Cemetery_in_2022.42.jp...
3759  0029_File_Small_Area_Atlas_of_Bangladesh_-_Ban...
896   0061_File_Small_Area_Atlas_of_Bangladesh_-_Ban...
843   0035_File_Small_Area_Atlas_of_Bangladesh_-_Ban...
3719  0108_File_Mainamati_War_Cemetery_in_2022.04.jp...
1750  0020_File_Mainamati_War_Cemetery_in_2022.04.jp...
3730  0119_File_Mainamati_War_Cemetery_in_2022.29.jp...
1797  0067_File_Mainamati_War_Cemetery_in_2022.29.jp...
5217  0019_File_A_supplement_to_the_Factehpur_gazett...
5031  0001_File_A_supplement_to_the_Factehpur_gazett...
832   0023_File_A_supplement_to_the_Factehpur_gazett...

                                                 sha256
113   0024e8ba15e5e654a662f82ab73c857f8fc6a8b8489a14...
3588  0024e8ba15e5e654a662f82ab73c857f8fc6a8b8489a14...
1749  01398da3e22ea5e84e3a1e3c5dbaf07715a8f13ac7b788...
3667  01398da3e22ea5e84e3a1e3c5dbaf07715a8f13ac7b788...
104   0335798647d7de3bf246da5e06d7aff5c846b150765a76...
3575  0335798647d7de3bf246da5e06d7aff5c846b150765a76...
1065  0482c1a5e2ab692168497d19e981cb5db008669696694c...
942   0482c1a5e2ab692168497d19e981cb5db008669696694c...
1757  04c721ed5a44bbcd68ecbe76395daf5a7dacb9cafa5980...
3672  04c721ed5a44bbcd68ecbe76395daf5a7dacb9cafa5980...
1820  069f22ca0e74b41ba4f237ffa88cfc1912541f836b63ae...
3709  069f22ca0e74b41ba4f237ffa88cfc1912541f836b63ae...
1741  06bf9940d458a7cf5b9d3426eee0af9284ae284eb90ee5...
3712  06bf9940d458a7cf5b9d3426eee0af9284ae284eb90ee5...
3589  0705302e5938b3d111359746dd3173dfb6fd0dfda5c011...
71    0705302e5938b3d111359746dd3173dfb6fd0dfda5c011...
3530  0b59cf8e94c5264953e2f02322b67d0a8ca6d37094c21d...
29    0b59cf8e94c5264953e2f02322b67d0a8ca6d37094c21d...
1776  0d217a74a6234c787d1af59cb2daff422e87d56dd19e98...
3685  0d217a74a6234c787d1af59cb2daff422e87d56dd19e98...
3759  0dca4fb4553bcf8f28f4141aa191fea3e26cfd43e99467...
896   0dca4fb4553bcf8f28f4141aa191fea3e26cfd43e99467...
843   0dca4fb4553bcf8f28f4141aa191fea3e26cfd43e99467...
3719  0eac983bf5a68e3b30bbf29da64276a20be9e9b9a709b0...
1750  0eac983bf5a68e3b30bbf29da64276a20be9e9b9a709b0...
3730  0f35c5ce46d911d604367b30720b2f5be50077d7f58c26...
1797  0f35c5ce46d911d604367b30720b2f5be50077d7f58c26...
5217  1063520b23a9d6e43d8d6473abc58cc12056e24f645f00...
5031  1063520b23a9d6e43d8d6473abc58cc12056e24f645f00...
832   1063520b23a9d6e43d8d6473abc58cc12056e24f645f00...

In [ ]:
CHECKPOINT = (
    "/content/drive/MyDrive/"
    "Chattogram_Landmark_Dataset/"
    "03_candidates/"
    "recovered_clean_metadata.csv"
)

clean_df.to_csv(
    CHECKPOINT,
    index=False
)

print("Checkpoint saved:")
print(CHECKPOINT)

Checkpoint saved:
/content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/recovered_clean_metadata.csv

In [ ]:
DUP_DIR = (
    "/content/drive/MyDrive/"
    "Chattogram_Landmark_Dataset/"
    "04_review/"
    "duplicate_analysis"
)

os.makedirs(
    DUP_DIR,
    exist_ok=True
)

print(DUP_DIR)

/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis

In [ ]:
phash_df = clean_df.copy()

phash_df = phash_df[
    phash_df["phash"].notna()
].copy()

phash_df["phash"] = (
    phash_df["phash"]
    .astype(str)
    .str.strip()
    .str.lower()
)

print("Records with pHash:", len(phash_df))
print("Unique pHash values:", phash_df["phash"].nunique())

Records with pHash: 5340
Unique pHash values: 5132

In [ ]:
print("pHash length distribution:")
print(
    phash_df["phash"]
    .str.len()
    .value_counts()
    .sort_index()
)

print("\nSample pHashes:")
print(
    phash_df["phash"]
    .head(10)
    .to_string(index=False)
)

pHash length distribution:
phash
16    5340
Name: count, dtype: int64

Sample pHashes:
d2cc2d36737c3283
ca28306fd37b348b
861877c2bdf22d19
85c3e2bc6c50ee93
fed54a9a9472829c
879de58ac91af454
aaf5b5a4cc532a4a
e2ecd78d94945cb0
d35d7cf221c85b82
d9dad8dbc3f29200

In [ ]:
sha_groups = (
    phash_df
    .groupby("sha256")
    .size()
    .reset_index(name="count")
)

exact_duplicate_groups = sha_groups[
    sha_groups["count"] > 1
].copy()

print("Exact duplicate groups:", len(exact_duplicate_groups))
print(
    "Images involved in exact duplicates:",
    exact_duplicate_groups["count"].sum()
)

Exact duplicate groups: 196
Images involved in exact duplicates: 398

In [ ]:
exact_duplicates_df = phash_df[
    phash_df["sha256"].isin(
        exact_duplicate_groups["sha256"]
    )
].sort_values("sha256")

exact_duplicates_path = os.path.join(
    DUP_DIR,
    "exact_duplicates.csv"
)

exact_duplicates_df.to_csv(
    exact_duplicates_path,
    index=False
)

print("Saved:")
print(exact_duplicates_path)

Saved:
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis/exact_duplicates.csv

In [ ]:
phash_groups = (
    phash_df
    .groupby("phash")
    .size()
    .reset_index(name="count")
)

repeated_phash = phash_groups[
    phash_groups["count"] > 1
].copy()

print("Repeated pHash groups:", len(repeated_phash))
print(
    "Images involved:",
    repeated_phash["count"].sum()
)

Repeated pHash groups: 198
Images involved: 406

In [ ]:
identical_phash_df = phash_df[
    phash_df["phash"].isin(
        repeated_phash["phash"]
    )
].sort_values("phash")

identical_phash_path = os.path.join(
    DUP_DIR,
    "identical_phash_groups.csv"
)

identical_phash_df.to_csv(
    identical_phash_path,
    index=False
)

print("Saved:")
print(identical_phash_path)

Saved:
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis/identical_phash_groups.csv

In [ ]:
def phash_to_int(phash):
    try:
        return int(phash, 16)
    except Exception:
        return None


phash_df["phash_int"] = phash_df["phash"].apply(phash_to_int)

invalid_phash = phash_df[
    phash_df["phash_int"].isna()
]

print("Invalid pHash values:", len(invalid_phash))

Invalid pHash values: 0

In [ ]:
def hamming_distance(a, b):
    return (a ^ b).bit_count()

print("Hamming function ready.")

Hamming function ready.

In [ ]:
import numpy as np

SEGMENT_BITS = 9

# Make sure pHash values are integer
phash_values = phash_df["phash_int"].astype(np.uint64).to_numpy()

segment_columns = []

for i in range(7):
    shift = i * SEGMENT_BITS
    col = f"seg_{i}"

    if shift < 64:
        phash_df[col] = (
            (phash_values >> np.uint64(shift))
            & np.uint64((1 << SEGMENT_BITS) - 1)
        ).astype(np.uint64)
    else:
        phash_df[col] = 0

    segment_columns.append(col)

print("Segment indexes created:")
print(segment_columns)

Segment indexes created:
['seg_0', 'seg_1', 'seg_2', 'seg_3', 'seg_4', 'seg_5', 'seg_6']

In [ ]:
from collections import defaultdict

MAX_DISTANCE = 6

candidate_pairs = set()

for segment in segment_columns:

    groups = phash_df.groupby(segment)

    for _, group in groups:

        indices = group.index.tolist()

        if len(indices) < 2:
            continue

        for i in range(len(indices)):
            idx1 = indices[i]
            hash1 = phash_df.at[idx1, "phash_int"]

            for j in range(i + 1, len(indices)):
                idx2 = indices[j]

                pair = (
                    min(idx1, idx2),
                    max(idx1, idx2)
                )

                candidate_pairs.add(pair)

print("Candidate pairs:", len(candidate_pairs))

Candidate pairs: 225616

In [ ]:
from tqdm.auto import tqdm
near_duplicate_pairs = []

for idx1, idx2 in tqdm(
    candidate_pairs,
    desc="Calculating Hamming distances"
):

    hash1 = phash_df.at[idx1, "phash_int"]
    hash2 = phash_df.at[idx2, "phash_int"]

    distance = hamming_distance(
        hash1,
        hash2
    )

    if distance <= MAX_DISTANCE:

        row1 = phash_df.loc[idx1]
        row2 = phash_df.loc[idx2]

        near_duplicate_pairs.append({
            "distance": distance,

            "landmark_1": row1["landmark"],
            "landmark_2": row2["landmark"],

            "district_1": row1["district"],
            "district_2": row2["district"],

            "filename_1": row1["filename"],
            "filename_2": row2["filename"],

            "path_1": row1["path"],
            "path_2": row2["path"],

            "phash_1": row1["phash"],
            "phash_2": row2["phash"]
        })

near_duplicates_df = pd.DataFrame(
    near_duplicate_pairs
)

print(
    "Near-duplicate pairs found:",
    len(near_duplicates_df)
)

Calculating Hamming distances:   0%|          | 0/225616 [00:00<?, ?it/s]

Near-duplicate pairs found: 303

In [ ]:
if len(near_duplicates_df) > 0:

    print("Hamming distance distribution:")
    print(
        near_duplicates_df[
            "distance"
        ]
        .value_counts()
        .sort_index()
    )

else:

    print("No near-duplicate pairs found.")

Hamming distance distribution:
distance
0    225
2     60
4     15
6      3
Name: count, dtype: int64

In [ ]:
cross_class = near_duplicates_df[
    near_duplicates_df["landmark_1"] !=
    near_duplicates_df["landmark_2"]
].sort_values("distance")

print(
    "Cross-class near-duplicate pairs:",
    len(cross_class)
)

print(
    cross_class.head(100).to_string(index=False)
)

Cross-class near-duplicate pairs: 303
 distance                       landmark_1             landmark_2   district_1   district_2                                                                                                                        filename_1                                                                                                                        filename_2                                                                                                                                                                                                                   path_1                                                                                                                                                                                                                path_2          phash_1          phash_2
        0                  Kutubdia_Island    Kutubdia_Lighthouse   Coxs_Bazar   Coxs_Bazar                                                                                    0066_File_Lighthouse_Batighar_Kutubdia.jpg.jpg                                                                                    0002_File_Lighthouse_Batighar_Kutubdia.jpg.jpg                                                                                          /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Island/0066_File_Lighthouse_Batighar_Kutubdia.jpg.jpg                                                                                   /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Lighthouse/0002_File_Lighthouse_Batighar_Kutubdia.jpg.jpg bcd3cb29b8da64a0 bcd3cb29b8da64a0
        0                 Chandpur_Stadium            Titas_River     Chandpur Brahmanbaria                                                                 0061_File_Small_Area_Atlas_of_Bangladesh_-_Bandarban_Zila.pdf.jpg                                                              0011_File_Small_Area_Atlas_of_Bangladesh_-_Brahmanbaria_Zila.pdf.jpg                                                                      /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandpur_Stadium/0061_File_Small_Area_Atlas_of_Bangladesh_-_Bandarban_Zila.pdf.jpg                                                                     /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Titas_River/0011_File_Small_Area_Atlas_of_Bangladesh_-_Brahmanbaria_Zila.pdf.jpg aca2330e4e53f2ec aca2330e4e53f2ec
        0                   Adinath_Temple            Maheshkhali   Coxs_Bazar   Coxs_Bazar                                                                                                                0104_File_.jpg.jpg                                                                                                                0074_File_.jpg.jpg                                                                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Adinath_Temple/0104_File_.jpg.jpg                                                                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Maheshkhali/0074_File_.jpg.jpg dc1983d8c4cec5ae dc1983d8c4cec5ae
        0                    Itakhola_Mura            Titas_River      Cumilla Brahmanbaria                                                                 0112_File_Small_Area_Atlas_of_Bangladesh_-_Netrokona_Zila.pdf.jpg                                                              0011_File_Small_Area_Atlas_of_Bangladesh_-_Brahmanbaria_Zila.pdf.jpg                                                                         /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Itakhola_Mura/0112_File_Small_Area_Atlas_of_Bangladesh_-_Netrokona_Zila.pdf.jpg                                                                     /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Titas_River/0011_File_Small_Area_Atlas_of_Bangladesh_-_Brahmanbaria_Zila.pdf.jpg aca2330e4e53f2ec aca2330e4e53f2ec
        0                  Kutubdia_Island    Kutubdia_Lighthouse   Coxs_Bazar   Coxs_Bazar                                                                                            0056_File_Kutubdia_Batighar_14.jpg.jpg                                                                                            0012_File_Kutubdia_Batighar_14.jpg.jpg                                                                                                  /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Island/0056_File_Kutubdia_Batighar_14.jpg.jpg                                                                                           /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Lighthouse/0012_File_Kutubdia_Batighar_14.jpg.jpg e18d2d7373906366 e18d2d7373906366
        0                   Adinath_Temple            Maheshkhali   Coxs_Bazar   Coxs_Bazar                                                                                                0006_File_Adinath_temple_2.JPG.jpg                                                                                                0002_File_Adinath_temple_2.JPG.jpg                                                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Adinath_Temple/0006_File_Adinath_temple_2.JPG.jpg                                                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Maheshkhali/0002_File_Adinath_temple_2.JPG.jpg 879de58ac91af454 879de58ac91af454
        0                  Kutubdia_Island            Wagga_Point   Coxs_Bazar    Rangamati                                                                 0098_File_Small_Area_Atlas_of_Bangladesh_-_Rangamati_Zila.pdf.jpg                                                                 0003_File_Small_Area_Atlas_of_Bangladesh_-_Rangamati_Zila.pdf.jpg                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Island/0098_File_Small_Area_Atlas_of_Bangladesh_-_Rangamati_Zila.pdf.jpg                                                                        /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Wagga_Point/0003_File_Small_Area_Atlas_of_Bangladesh_-_Rangamati_Zila.pdf.jpg eca2330e4e13f2ec eca2330e4e13f2ec
        0  Comilla_Cantonment_War_Cemetery       Mainamati_Museum      Cumilla      Cumilla                                                                                 0073_File_The_Mainamati_War_Cemetery_sign.jpg.jpg                                                                                 0081_File_The_Mainamati_War_Cemetery_sign.jpg.jpg                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Comilla_Cantonment_War_Cemetery/0073_File_The_Mainamati_War_Cemetery_sign.jpg.jpg                                                                                   /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Mainamati_Museum/0081_File_The_Mainamati_War_Cemetery_sign.jpg.jpg 9da249c596fab816 9da249c596fab816
        0                 Chandpur_Stadium          Itakhola_Mura     Chandpur      Cumilla                                                                 0061_File_Small_Area_Atlas_of_Bangladesh_-_Bandarban_Zila.pdf.jpg                                                                 0112_File_Small_Area_Atlas_of_Bangladesh_-_Netrokona_Zila.pdf.jpg                                                                      /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandpur_Stadium/0061_File_Small_Area_Atlas_of_Bangladesh_-_Bandarban_Zila.pdf.jpg                                                                      /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Itakhola_Mura/0112_File_Small_Area_Atlas_of_Bangladesh_-_Netrokona_Zila.pdf.jpg aca2330e4e53f2ec aca2330e4e53f2ec
        0                 Chandranath_Hill     Chandranath_Temple   Chattogram   Chattogram                                                                              0007_File_Chandranath_and_Birupaksha_Temples.jpg.jpg                                                                              0067_File_Chandranath_and_Birupaksha_Temples.jpg.jpg                                                                                   /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandranath_Hill/0007_File_Chandranath_and_Birupaksha_Temples.jpg.jpg                                                                              /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandranath_Temple/0067_File_Chandranath_and_Birupaksha_Temples.jpg.jpg b6e946106db64dd2 b6e946106db64dd2
        0                   Adinath_Temple            Maheshkhali   Coxs_Bazar   Coxs_Bazar                                                                       0011_File_First_gate_of_Adinath_Temple_Moheshkhali_.jpg.jpg                                                                       0022_File_First_gate_of_Adinath_Temple_Moheshkhali_.jpg.jpg                                                                              /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Adinath_Temple/0011_File_First_gate_of_Adinath_Temple_Moheshkhali_.jpg.jpg                                                                              /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Maheshkhali/0022_File_First_gate_of_Adinath_Temple_Moheshkhali_.jpg.jpg dc2baf74825bb520 dc2baf74825bb520
        0  Comilla_Cantonment_War_Cemetery       Mainamati_Museum      Cumilla      Cumilla                                                                  0085_File_The_Mainamati_War_Cemetery_close_grave_signage.jpg.jpg                                                                  0093_File_The_Mainamati_War_Cemetery_close_grave_signage.jpg.jpg                                                        /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Comilla_Cantonment_War_Cemetery/0085_File_The_Mainamati_War_Cemetery_close_grave_signage.jpg.jpg                                                                    /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Mainamati_Museum/0093_File_The_Mainamati_War_Cemetery_close_grave_signage.jpg.jpg 852f7ee0308df358 852f7ee0308df358
        0                 Coxs_Bazar_Beach            Inani_Beach   Coxs_Bazar   Coxs_Bazar                                                                                         0028_File_Inani_Beach_Cox_s_Bazar.jpg.jpg                                                                                         0022_File_Inani_Beach_Cox_s_Bazar.jpg.jpg                                                                                              /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Coxs_Bazar_Beach/0028_File_Inani_Beach_Cox_s_Bazar.jpg.jpg                                                                                                /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Inani_Beach/0022_File_Inani_Beach_Cox_s_Bazar.jpg.jpg c6dd39260299fdc2 c6dd39260299fdc2
        0  Comilla_Cantonment_War_Cemetery       Mainamati_Museum      Cumilla      Cumilla                                                                          0088_File_The_Mainamati_War_Cemetery_flowe_grave.jpg.jpg                                                                          0096_File_The_Mainamati_War_Cemetery_flowe_grave.jpg.jpg                                                                /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Comilla_Cantonment_War_Cemetery/0088_File_The_Mainamati_War_Cemetery_flowe_grave.jpg.jpg                                                                            /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Mainamati_Museum/0096_File_The_Mainamati_War_Cemetery_flowe_grave.jpg.jpg 81af7af03295b15a 81af7af03295b15a
        0                   Adinath_Temple            Maheshkhali   Coxs_Bazar   Coxs_Bazar                                                                              0026_File_Adi_Nath_temple_gate_Moheshkhali01.jpg.jpg                                                                              0027_File_Adi_Nath_temple_gate_Moheshkhali01.jpg.jpg                                                                                     /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Adinath_Temple/0026_File_Adi_Nath_temple_gate_Moheshkhali01.jpg.jpg                                                                                     /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Maheshkhali/0027_File_Adi_Nath_temple_gate_Moheshkhali01.jpg.jpg c800d77e91c59a7b c800d77e91c59a7b
        0                  Kutubdia_Island    Kutubdia_Lighthouse   Coxs_Bazar   Coxs_Bazar                                                                                             0065_File_Kutubdia_lighthouse.jpg.jpg                                                                                             0001_File_Kutubdia_lighthouse.jpg.jpg                                                                                                   /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Island/0065_File_Kutubdia_lighthouse.jpg.jpg                                                                                            /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Lighthouse/0001_File_Kutubdia_lighthouse.jpg.jpg d0e72d58ad2fd025 d0e72d58ad2fd025
        0  Comilla_Cantonment_War_Cemetery       Mainamati_Museum      Cumilla      Cumilla                                                                                 0074_File_The_Mainamati_War_Cemetery_view.jpg.jpg                                                                                 0082_File_The_Mainamati_War_Cemetery_view.jpg.jpg                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Comilla_Cantonment_War_Cemetery/0074_File_The_Mainamati_War_Cemetery_view.jpg.jpg                                                                                   /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Mainamati_Museum/0082_File_The_Mainamati_War_Cemetery_view.jpg.jpg 8795786a6a689c97 8795786a6a689c97
        0                     Alutila_Cave         Alutila_Tunnel Khagrachhari Khagrachhari                                                                                      0001_File_Alutila_Tunnel_Khagrachori.jpg.jpg                                                                                      0001_File_Alutila_Tunnel_Khagrachori.jpg.jpg                                                                                               /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Alutila_Cave/0001_File_Alutila_Tunnel_Khagrachori.jpg.jpg                                                                                          /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Alutila_Tunnel/0001_File_Alutila_Tunnel_Khagrachori.jpg.jpg f6cb8d86c1955554 f6cb8d86c1955554
        0            Chandpur_Boro_Station            Titas_River     Chandpur Brahmanbaria                                                                 0035_File_Small_Area_Atlas_of_Bangladesh_-_Bandarban_Zila.pdf.jpg                                                              0011_File_Small_Area_Atlas_of_Bangladesh_-_Brahmanbaria_Zila.pdf.jpg                                                                 /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chandpur_Boro_Station/0035_File_Small_Area_Atlas_of_Bangladesh_-_Bandarban_Zila.pdf.jpg                                                                     /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Titas_River/0011_File_Small_Area_Atlas_of_Bangladesh_-_Brahmanbaria_Zila.pdf.jpg aca2330e4e53f2ec aca2330e4e53f2ec
        0                     Chimbuk_Hill Meghla_Tourist_Complex    Bandarban    Bandarban                                                                                       0036_File_Chimbuk_Tourist_Center_1_.jpg.jpg                                                                                       0003_File_Chimbuk_Tourist_Center_1_.jpg.jpg                                                                                                /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Chimbuk_Hill/0036_File_Chimbuk_Tourist_Center_1_.jpg.jpg                                                                                   /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Meghla_Tourist_Complex/0003_File_Chimbuk_Tourist_Center_1_.jpg.jpg a028bfdf4525a36a a028bfdf4525a36a
        0  Comilla_Cantonment_War_Cemetery       Mainamati_Museum      Cumilla      Cumilla                                                                               0066_File_Mainamati_War_Cemetery_in_2022.24.jpg.jpg                                                                               0117_File_Mainamati_War_Cemetery_in_2022.24.jpg.jpg                                                                     /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Comilla_Cantonment_War_Cemetery/0066_File_Mainamati_War_Cemetery_in_2022.24.jpg.jpg                                                                                 /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Mainamati_Museum/0117_File_Mainamati_War_Cemetery_in_2022.24.jpg.jpg c1606bc3e795166e c1606bc3e795166e
        0                   Adinath_Temple            Maheshkhali   Coxs_Bazar   Coxs_Bazar                                                                                                                0111_File_.jpg.jpg                                                                                                                0084_File_.jpg.jpg                                                                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Adinath_Temple/0111_File_.jpg.jpg                                                                                                                       /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Maheshkhali/0084_File_.jpg.jpg 9559d0378734966e 9559d0378734966e
        0                  Kutubdia_Island    Kutubdia_Lighthouse   Coxs_Bazar   Coxs_Bazar                                                                                            0049_File_Kutubdia_Batighar_06.jpg.jpg                                                                                            0007_File_Kutubdia_Batighar_06.jpg.jpg                                                                                                  /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Island/0049_File_Kutubdia_Batighar_06.jpg.jpg                                                                                           /content/drive/MyDrive/Chattogram_Landmark_Dataset/03_candidates/Kutubdia_Lighthouse/0007_File_Kutubdia_Batighar_06.jpg.jpg 8aad9d6aea8312ec 8aad9d6aea8312ec

In [ ]:
near_duplicate_path = os.path.join(
    DUP_DIR,
    "near_duplicate_pairs.csv"
)

near_duplicates_df.to_csv(
    near_duplicate_path,
    index=False
)

print("Saved:")
print(near_duplicate_path)

Saved:
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis/near_duplicate_pairs.csv

In [ ]:
same_class = near_duplicates_df[
    near_duplicates_df["landmark_1"] == near_duplicates_df["landmark_2"]
].copy()

cross_class = near_duplicates_df[
    near_duplicates_df["landmark_1"] != near_duplicates_df["landmark_2"]
].copy()

print("Same-class near-duplicate pairs:", len(same_class))
print("Cross-class near-duplicate pairs:", len(cross_class))

print("\nCross-class pairs by Hamming distance:")
print(
    cross_class["distance"]
    .value_counts()
    .sort_index()
)

Same-class near-duplicate pairs: 0
Cross-class near-duplicate pairs: 303

Cross-class pairs by Hamming distance:
distance
0    225
2     60
4     15
6      3
Name: count, dtype: int64

In [ ]:
cross_pair_summary = (
    cross_class
    .groupby(
        ["landmark_1", "landmark_2"]
    )
    .agg(
        pairs=("distance", "size"),
        min_distance=("distance", "min"),
        max_distance=("distance", "max")
    )
    .reset_index()
    .sort_values(
        ["pairs", "min_distance"],
        ascending=[False, True]
    )
)

print(
    "Number of cross-class landmark pairs:",
    len(cross_pair_summary)
)

print(
    cross_pair_summary.to_string(index=False)
)

Number of cross-class landmark pairs: 129
                      landmark_1                 landmark_2  pairs  min_distance  max_distance
 Comilla_Cantonment_War_Cemetery           Mainamati_Museum     61             0             0
                  Adinath_Temple                Maheshkhali     46             0             0
                 Kutubdia_Island        Kutubdia_Lighthouse     18             0             0
                Chandranath_Hill         Chandranath_Temple     17             0             0
           Chandpur_Boro_Station         Three_Rivers_Mouth     15             0             0
                      Kaptai_Dam                Kaptai_Lake      5             0             0
                 Kutubdia_Island                Maheshkhali      4             0             4
                Chandranath_Hill           Guliakhali_Beach      3             0             0
                    Chimbuk_Hill     Meghla_Tourist_Complex      3             0             0
                Kamalnagar_Coast              Ramgati_Beach      3             0             0
          Meghla_Tourist_Complex   Rangamati_Hanging_Bridge      3             0             0
        Central_Railway_Building Chattogram_Railway_Station      2             0             0
        Central_Railway_Building             Chattogram_Zoo      2             0             2
           Chandpur_Boro_Station  Dalal_Bazar_Jamindar_Bari      2             0             2
Chattogram_Central_Shaheed_Minar                  Foys_Lake      2             0             0
                Coxs_Bazar_Beach                Inani_Beach      2             0             0
                    Lalmai_Hills             Shalban_Vihara      2             0             0
                     Maheshkhali             Sonadia_Island      2             0             2
                    Alutila_Cave             Alutila_Tunnel      1             0             0
                    Alutila_Cave            Kutubdia_Island      1             0             0
                    Alutila_Cave                Wagga_Point      1             0             0
                        Amiakhum         Nafakhum_Waterfall      1             0             0
                     Batali_Hill           Chandranath_Hill      1             0             0
          Bayazid_Bostami_Shrine             Chattogram_Zoo      1             0             0
                       Boga_Lake                 Keokradong      1             0             0
           Chandpur_Boro_Station           Chandpur_Stadium      1             0             0
           Chandpur_Boro_Station         Chandranath_Temple      1             0             0
           Chandpur_Boro_Station Chattogram_Railway_Station      1             0             0
           Chandpur_Boro_Station              Itakhola_Mura      1             0             0
           Chandpur_Boro_Station     Meghla_Tourist_Complex      1             0             0
           Chandpur_Boro_Station             Muhuri_Project      1             0             0
           Chandpur_Boro_Station       Shamsher_Gazi_Mosque      1             0             0
           Chandpur_Boro_Station                Titas_River      1             0             0
                Chandpur_Stadium  Dalal_Bazar_Jamindar_Bari      1             0             0
                Chandpur_Stadium              Itakhola_Mura      1             0             0
                Chandpur_Stadium     Meghla_Tourist_Complex      1             0             0
                Chandpur_Stadium         Three_Rivers_Mouth      1             0             0
                Chandpur_Stadium                Titas_River      1             0             0
              Chandranath_Temple             Muhuri_Project      1             0             0
              Chandranath_Temple         Three_Rivers_Mouth      1             0             0
      Chattogram_Railway_Station         Three_Rivers_Mouth      1             0             0
                  Chattogram_Zoo                  Foys_Lake      1             0             0
                    Chimbuk_Hill                    Nilgiri      1             0             0
                Coxs_Bazar_Beach             Sonadia_Island      1             0             0
       Dalal_Bazar_Jamindar_Bari              Itakhola_Mura      1             0             0
       Dalal_Bazar_Jamindar_Bari     Meghla_Tourist_Complex      1             0             0
       Dalal_Bazar_Jamindar_Bari                Titas_River      1             0             0
                   Itakhola_Mura     Meghla_Tourist_Complex      1             0             0
                   Itakhola_Mura                Titas_River      1             0             0
                Kamalnagar_Coast                Maheshkhali      1             0             0
                     Kaptai_Lake   Rangamati_Hanging_Bridge      1             0             0
                 Kutubdia_Island                Wagga_Point      1             0             0
                     Maheshkhali              Ramgati_Beach      1             0             0
          Meghla_Tourist_Complex                Titas_River      1             0             0
                  Muhuri_Project         Three_Rivers_Mouth      1             0             0
            Shamsher_Gazi_Mosque         Three_Rivers_Mouth      1             0             0
                    Alutila_Cave      Chandpur_Boro_Station      1             2             2
                    Alutila_Cave           Chandpur_Stadium      1             2             2
                    Alutila_Cave  Dalal_Bazar_Jamindar_Bari      1             2             2
                    Alutila_Cave              Itakhola_Mura      1             2             2
                    Alutila_Cave     Meghla_Tourist_Complex      1             2             2
                    Alutila_Cave             Sonadia_Island      1             2             2
                    Alutila_Cave                Titas_River      1             2             2
                Banshbaria_Beach      Chandpur_Boro_Station      1             2             2
                Banshbaria_Beach           Chandpur_Stadium      1             2             2
                Banshbaria_Beach  Dalal_Bazar_Jamindar_Bari      1             2             2
                Banshbaria_Beach              Itakhola_Mura      1             2             2
                Banshbaria_Beach           Kamalnagar_Coast      1             2             2
                Banshbaria_Beach                Maheshkhali      1             2             2
                Banshbaria_Beach     Meghla_Tourist_Complex      1             2             2
                Banshbaria_Beach              Ramgati_Beach      1             2             2
                Banshbaria_Beach             Sonadia_Island      1             2             2
                Banshbaria_Beach                Titas_River      1             2             2
           Chandpur_Boro_Station           Kamalnagar_Coast      1             2             2
           Chandpur_Boro_Station            Kutubdia_Island      1             2             2
           Chandpur_Boro_Station                Maheshkhali      1             2             2
           Chandpur_Boro_Station              Ramgati_Beach      1             2             2
           Chandpur_Boro_Station             Sonadia_Island      1             2             2
           Chandpur_Boro_Station                Wagga_Point      1             2             2
                Chandpur_Stadium           Kamalnagar_Coast      1             2             2
                Chandpur_Stadium            Kutubdia_Island      1             2             2
                Chandpur_Stadium                Maheshkhali      1             2             2
                Chandpur_Stadium              Ramgati_Beach      1             2             2
                Chandpur_Stadium             Sonadia_Island      1             2             2
                Chandpur_Stadium                Wagga_Point      1             2             2
       Dalal_Bazar_Jamindar_Bari           Kamalnagar_Coast      1             2             2
       Dalal_Bazar_Jamindar_Bari            Kutubdia_Island      1             2             2
       Dalal_Bazar_Jamindar_Bari                Maheshkhali      1             2             2
       Dalal_Bazar_Jamindar_Bari              Ramgati_Beach      1             2             2
       Dalal_Bazar_Jamindar_Bari             Sonadia_Island      1             2             2
       Dalal_Bazar_Jamindar_Bari                Wagga_Point      1             2             2
                   Itakhola_Mura           Kamalnagar_Coast      1             2             2
                   Itakhola_Mura            Kutubdia_Island      1             2             2
                   Itakhola_Mura                Maheshkhali      1             2             2
                   Itakhola_Mura              Ramgati_Beach      1             2             2
                   Itakhola_Mura             Sonadia_Island      1             2             2
                   Itakhola_Mura                Wagga_Point      1             2             2
                Kamalnagar_Coast     Meghla_Tourist_Complex      1             2             2
                Kamalnagar_Coast             Sonadia_Island      1             2             2
                Kamalnagar_Coast                Titas_River      1             2             2
                 Kutubdia_Island     Meghla_Tourist_Complex      1             2             2
                 Kutubdia_Island             Sonadia_Island      1             2             2
                 Kutubdia_Island                Titas_River      1             2             2
                     Maheshkhali     Meghla_Tourist_Complex      1             2             2
                     Maheshkhali                Titas_River      1             2             2
          Meghla_Tourist_Complex              Ramgati_Beach      1             2             2
          Meghla_Tourist_Complex             Sonadia_Island      1             2             2
          Meghla_Tourist_Complex                Wagga_Point      1             2             2
                   Ramgati_Beach             Sonadia_Island      1             2             2
                   Ramgati_Beach                Titas_River      1             2             2
                  Sonadia_Island                Titas_River      1             2             2
                  Sonadia_Island                Wagga_Point      1             2             2
                     Titas_River                Wagga_Point      1             2             2
                    Alutila_Cave           Banshbaria_Beach      1             4             4
                    Alutila_Cave           Kamalnagar_Coast      1             4             4
                    Alutila_Cave                Maheshkhali      1             4             4
                    Alutila_Cave              Ramgati_Beach      1             4             4
                  Anderson_Canal   Central_Railway_Building      1             4             4
                Banshbaria_Beach            Kutubdia_Island      1             4             4
                Banshbaria_Beach                Wagga_Point      1             4             4
                Kamalnagar_Coast            Kutubdia_Island      1             4             4
                Kamalnagar_Coast                Wagga_Point      1             4             4
                 Kutubdia_Island              Ramgati_Beach      1             4             4
                     Maheshkhali                Wagga_Point      1             4             4
                Mong_King_Palace             Peda_Ting_Ting      1             4             4
                   Ramgati_Beach                Wagga_Point      1             4             4
                  Anderson_Canal             Chattogram_Zoo      1             6             6
                  Chattogram_Zoo           Mong_King_Palace      1             6             6
                  Chattogram_Zoo              Ramgati_Beach      1             6             6

In [ ]:
problematic_classes = pd.concat([
    cross_class["landmark_1"],
    cross_class["landmark_2"]
]).value_counts()

print(
    "Classes involved in cross-class near duplicates:"
)

print(problematic_classes.to_string())

Classes involved in cross-class near duplicates:
Maheshkhali                         63
Comilla_Cantonment_War_Cemetery     61
Mainamati_Museum                    61
Adinath_Temple                      46
Kutubdia_Island                     34
Chandpur_Boro_Station               33
Chandranath_Hill                    21
Three_Rivers_Mouth                  20
Chandranath_Temple                  20
Meghla_Tourist_Complex              19
Kutubdia_Lighthouse                 18
Ramgati_Beach                       16
Kamalnagar_Coast                    15
Sonadia_Island                      15
Alutila_Cave                        14
Chandpur_Stadium                    14
Dalal_Bazar_Jamindar_Bari           14
Titas_River                         13
Wagga_Point                         13
Banshbaria_Beach                    13
Itakhola_Mura                       13
Chattogram_Zoo                       7
Kaptai_Lake                          6
Kaptai_Dam                           5
Central_Railway_Building             5
Chimbuk_Hill                         4
Rangamati_Hanging_Bridge             4
Chattogram_Railway_Station           4
Guliakhali_Beach                     3
Muhuri_Project                       3
Foys_Lake                            3
Coxs_Bazar_Beach                     3
Lalmai_Hills                         2
Chattogram_Central_Shaheed_Minar     2
Mong_King_Palace                     2
Shamsher_Gazi_Mosque                 2
Shalban_Vihara                       2
Inani_Beach                          2
Anderson_Canal                       2
Bayazid_Bostami_Shrine               1
Boga_Lake                            1
Amiakhum                             1
Batali_Hill                          1
Nilgiri                              1
Peda_Ting_Ting                       1
Alutila_Tunnel                       1
Nafakhum_Waterfall                   1
Keokradong                           1

In [ ]:
# Get all image paths involved in cross-class near duplicates

cross_paths = pd.unique(
    pd.concat([
        cross_class["path_1"],
        cross_class["path_2"]
    ], ignore_index=True)
)

print("Unique images involved in cross-class near duplicates:", len(cross_paths))

Unique images involved in cross-class near duplicates: 421

In [ ]:
cross_review = phash_df[
    phash_df["path"].isin(cross_paths)
].copy()

print("Images found in metadata:", len(cross_review))

cross_review[
    [
        "landmark",
        "district",
        "filename",
        "path",
        "title",
        "file_url",
        "description_url",
        "license",
        "artist",
        "width",
        "height"
    ]
].head(20)

Images found in metadata: 421

,landmark,district,filename,path,title,file_url,description_url,license,artist,width,height
0,Adinath_Temple,Coxs_Bazar,0001_File_Moheshkhali_adinath_temple01.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Moheshkhali adinath temple01.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Mohesh...,Public domain,"<a href=""//commons.wikimedia.org/wiki/User:Mun...",1536.0,2048.0
1,Adinath_Temple,Coxs_Bazar,0002_File_Moheshkhali_adinath_temple02.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Moheshkhali adinath temple02.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Mohesh...,Public domain,"<a href=""//commons.wikimedia.org/wiki/User:Mun...",1536.0,2048.0
2,Adinath_Temple,Coxs_Bazar,0003_File_Moheshkhali00005.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Moheshkhali00005.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Mohesh...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Bel...",2048.0,1536.0
4,Adinath_Temple,Coxs_Bazar,0005_File_Adinath_temple_1.JPG.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Adinath temple 1.JPG,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adinat...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Tan...",4272.0,2848.0
5,Adinath_Temple,Coxs_Bazar,0006_File_Adinath_temple_2.JPG.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Adinath temple 2.JPG,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adinat...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Tan...",2000.0,1333.0
8,Adinath_Temple,Coxs_Bazar,0009_File_Adinath_Temple_in_Moheshkhali_.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Adinath Temple in Moheshkhali .jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adinat...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Sal...",4160.0,3120.0
9,Adinath_Temple,Coxs_Bazar,0010_File_Adinath_Temple_Moheshkhali_.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adinath Temple, Moheshkhali .jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adinat...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Sal...",4160.0,3120.0
10,Adinath_Temple,Coxs_Bazar,0011_File_First_gate_of_Adinath_Temple_Moheshk...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:First gate of Adinath Temple, Moheshkhali...",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:First_...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Sal...",4160.0,3120.0
11,Adinath_Temple,Coxs_Bazar,0012_File_Adinath_Temple_premises_.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Adinath Temple premises .jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adinat...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Sal...",4160.0,3120.0
12,Adinath_Temple,Coxs_Bazar,0013_File_Adinath_Temple_premises_2.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Adinath Temple premises 2.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adinat...,CC BY-SA 3.0,"<a href=""//commons.wikimedia.org/wiki/User:Sal...",4160.0,3120.0
13,Adinath_Temple,Coxs_Bazar,0014_File_Adinath_Temple_located_at_Maheshkhal...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:Adinath Temple located at Maheshkhali.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adinat...,CC BY-SA 4.0,"<a href=""//commons.wikimedia.org/wiki/User:Sye...",6000.0,4000.0
14,Adinath_Temple,Coxs_Bazar,0015_File_.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,File:আদিনাথ মন্দির ৪৫.jpg,https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:%E0%A6...,CC BY-SA 4.0,"<a href=""//commons.wikimedia.org/w/index.php?t...",5760.0,3840.0
15,Adinath_Temple,Coxs_Bazar,0016_File_The_stairs_of_heaven_Adinath_mondir....,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:The stairs of heaven,Adinath mondir.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:The_st...,CC BY-SA 4.0,"<a href=""//commons.wikimedia.org/w/index.php?t...",4032.0,3024.0
23,Adinath_Temple,Coxs_Bazar,0024_File_Adi_Nath_temple_gate_Moheshkhali.jpg...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adi Nath temple gate, Moheshkhali.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adi_Na...,CC BY-SA 4.0,"<p><a href=""//commons.wikimedia.org/wiki/User:...",4128.0,3096.0
24,Adinath_Temple,Coxs_Bazar,0025_File_Adi_Nath_temple_gate_Moheshkhali02.j...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adi Nath temple gate, Moheshkhali02.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adi_Na...,CC BY-SA 4.0,"<p><a href=""//commons.wikimedia.org/wiki/User:...",4128.0,3096.0
25,Adinath_Temple,Coxs_Bazar,0026_File_Adi_Nath_temple_gate_Moheshkhali01.j...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adi Nath temple gate, Moheshkhali01.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adi_Na...,CC BY-SA 4.0,"<p><a href=""//commons.wikimedia.org/wiki/User:...",4128.0,3096.0
26,Adinath_Temple,Coxs_Bazar,0027_File_Adi_Nath_temple_worship_flower_Mohes...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adi Nath temple worship flower, Moheshkha...",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adi_Na...,CC BY-SA 4.0,"<p><a href=""//commons.wikimedia.org/wiki/User:...",4128.0,3096.0
27,Adinath_Temple,Coxs_Bazar,0028_File_Adi_Nath_temple_Moheshkhali.jpg.jpg,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adi Nath temple, Moheshkhali.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adi_Na...,CC BY-SA 4.0,"<p><a href=""//commons.wikimedia.org/wiki/User:...",4128.0,3096.0
28,Adinath_Temple,Coxs_Bazar,0029_File_Adi_Nath_temple_2nd_gate_Moheshkhali...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adi Nath temple 2nd gate, Moheshkhali.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adi_Na...,CC BY-SA 4.0,"<p><a href=""//commons.wikimedia.org/wiki/User:...",4128.0,3096.0
29,Adinath_Temple,Coxs_Bazar,0030_File_Adi_Nath_temple_tree_Moheshkhali.jpg...,/content/drive/MyDrive/Chattogram_Landmark_Dat...,"File:Adi Nath temple tree, Moheshkhali.jpg",https://upload.wikimedia.org/wikipedia/commons...,https://commons.wikimedia.org/wiki/File:Adi_Na...,CC BY-SA 4.0,"<p><a href=""//commons.wikimedia.org/wiki/User:...",4128.0,3096.0

In [ ]:
import re

text_cols = [
    "filename",
    "title",
    "description_url",
    "file_url"
]

review_text = (
    cross_review[text_cols]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

suspicious_pattern = (
    r"\.pdf|pdf|atlas|gazetteer|journal|book|"
    r"historical|report|map|document|magazine"
)

cross_review["suspicious_source"] = (
    review_text.str.contains(
        suspicious_pattern,
        regex=True,
        na=False
    )
)

print(
    "Potentially suspicious source images:"
)

print(
    cross_review[
        "suspicious_source"
    ].value_counts()
)

print(
    "\nSuspicious images:"
)

display(
    cross_review[
        cross_review["suspicious_source"]
    ][
        [
            "landmark",
            "filename",
            "title",
            "description_url"
        ]
    ].head(100)
)

Potentially suspicious source images:
suspicious_source
False    356
True      65
Name: count, dtype: int64

Suspicious images:

,landmark,filename,title,description_url
149,Alutila_Cave,0033_File_Small_Area_Atlas_of_Bangladesh_-_Kha...,File:Small Area Atlas of Bangladesh - Khagrach...,https://commons.wikimedia.org/wiki/File:Small_...
269,Anderson_Canal,0012_File_United_States_Civil_Aircraft_Registe...,File:United States Civil Aircraft Register Jan...,https://commons.wikimedia.org/wiki/File:United...
402,Banshbaria_Beach,0045_File_Small_Area_Atlas_of_Bangladesh_-_Bag...,File:Small Area Atlas of Bangladesh - Bagerhat...,https://commons.wikimedia.org/wiki/File:Small_...
557,Bayazid_Bostami_Shrine,0048_File_Journal_of_the_Bombay_Natural_Histor...,File:Journal of the Bombay Natural History Soc...,https://commons.wikimedia.org/wiki/File:Journa...
754,Central_Railway_Building,0097_File_The_New_York_Times_1930-04-28-_Vol_7...,File:The New York Times 1930-04-28- Vol 79 Iss...,https://commons.wikimedia.org/wiki/File:The_Ne...
...,...,...,...,...
5218,Three_Rivers_Mouth,0020_File_Board_of_Trade_Journal._London._1922...,File:Board of Trade Journal. London. 1922-06-0...,https://commons.wikimedia.org/wiki/File:Board_...
5223,Three_Rivers_Mouth,0025_File_Behar_Herald_8-12-2020_15-12-2020.pd...,File:Behar Herald 8-12-2020 & 15-12-2020.pdf,https://commons.wikimedia.org/wiki/File:Behar_...
5227,Three_Rivers_Mouth,0029_File_November_1961_-_DPLA_-_19f370327836f...,File:November 1961 - DPLA - 19f370327836f9576e...,https://commons.wikimedia.org/wiki/File:Novemb...
5237,Titas_River,0011_File_Small_Area_Atlas_of_Bangladesh_-_Bra...,File:Small Area Atlas of Bangladesh - Brahmanb...,https://commons.wikimedia.org/wiki/File:Small_...
5335,Wagga_Point,0003_File_Small_Area_Atlas_of_Bangladesh_-_Ran...,File:Small Area Atlas of Bangladesh - Rangamat...,https://commons.wikimedia.org/wiki/File:Small_...

In [ ]:
SOURCE_REVIEW_DIR = (
    "/content/drive/MyDrive/"
    "Chattogram_Landmark_Dataset/"
    "04_review/"
    "duplicate_analysis"
)

os.makedirs(SOURCE_REVIEW_DIR, exist_ok=True)

review_csv = os.path.join(
    SOURCE_REVIEW_DIR,
    "cross_class_contamination_review.csv"
)

cross_review.to_csv(
    review_csv,
    index=False
)

print("Saved:")
print(review_csv)

Saved:
/content/drive/MyDrive/Chattogram_Landmark_Dataset/04_review/duplicate_analysis/cross_class_contamination_review.csv